import { MediaType, MediaStatus } from "@prisma/client";

export const animeTitles = [
  // Shonen Action
  {
    canonicalTitle: "Fullmetal Alchemist: Brotherhood",
    originalTitle: "鋼の錬金術師 FULLMETAL ALCHEMIST",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2009,
    endYear: 2010,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy", "Drama"]),
    description: "Two brothers use alchemy in their quest to restore their bodies, uncovering a vast conspiracy threatening their nation.",
    rating: 9.1,
    popularity: 95000,
    episodeCount: 64,
    sourceUrl: "https://anilist.co/anime/5114",
    sourceName: "AniList",
    externalId: "5114",
  },
  {
    canonicalTitle: "Demon Slayer: Kimetsu no Yaiba",
    originalTitle: "鬼滅の刃",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2019,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Supernatural", "Historical"]),
    description: "A boy becomes a demon slayer to save his sister after his family is slaughtered by demons.",
    rating: 8.7,
    popularity: 89000,
    episodeCount: 44,
    sourceUrl: "https://anilist.co/anime/101922",
    sourceName: "AniList",
    externalId: "101922",
  },
  {
    canonicalTitle: "Attack on Titan",
    originalTitle: "進撃の巨人",
    mediaType: MediaType.ANIME,
    subType: "Seinen",
    releaseYear: 2013,
    endYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Drama", "Fantasy", "Mystery"]),
    description: "Humanity fights for survival against giant humanoid Titans behind enormous walls.",
    rating: 9.0,
    popularity: 93000,
    episodeCount: 87,
    sourceUrl: "https://anilist.co/anime/16498",
    sourceName: "AniList",
    externalId: "16498",
  },
  {
    canonicalTitle: "Hunter x Hunter (2011)",
    originalTitle: "HUNTER×HUNTER",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2011,
    endYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy"]),
    description: "A young boy searches for his missing father, becoming a Hunter and uncovering a world of danger and wonder.",
    rating: 9.1,
    popularity: 90000,
    episodeCount: 148,
    sourceUrl: "https://anilist.co/anime/11061",
    sourceName: "AniList",
    externalId: "11061",
  },
  {
    canonicalTitle: "My Hero Academia",
    originalTitle: "僕のヒーローアカデミア",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Superhero", "School", "Comedy"]),
    description: "In a world where most people have superpowers, a powerless boy dreams of becoming the greatest hero.",
    rating: 7.9,
    popularity: 85000,
    episodeCount: 138,
    sourceUrl: "https://anilist.co/anime/21459",
    sourceName: "AniList",
    externalId: "21459",
  },
  {
    canonicalTitle: "Dragon Ball Z",
    originalTitle: "ドラゴンボールZ",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 1989,
    endYear: 1996,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy", "Martial Arts"]),
    description: "Goku and his allies defend Earth against increasingly powerful adversaries across the universe.",
    rating: 8.1,
    popularity: 82000,
    episodeCount: 291,
    sourceUrl: "https://anilist.co/anime/813",
    sourceName: "AniList",
    externalId: "813",
  },
  {
    canonicalTitle: "Jujutsu Kaisen",
    originalTitle: "呪術廻戦",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2020,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Supernatural", "Dark Fantasy"]),
    description: "A high school student swallows a cursed object and joins a secret organization of Jujutsu Sorcerers.",
    rating: 8.7,
    popularity: 88000,
    episodeCount: 47,
    sourceUrl: "https://anilist.co/anime/113415",
    sourceName: "AniList",
    externalId: "113415",
  },
  {
    canonicalTitle: "Bleach",
    originalTitle: "ブリーチ",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2004,
    endYear: 2012,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Supernatural", "Adventure"]),
    description: "A teenager gains Soul Reaper powers and must defend the living world from evil spirits.",
    rating: 7.9,
    popularity: 75000,
    episodeCount: 366,
    sourceUrl: "https://anilist.co/anime/269",
    sourceName: "AniList",
    externalId: "269",
  },
  {
    canonicalTitle: "One Piece",
    originalTitle: "ワンピース",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 1999,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy", "Comedy"]),
    description: "Monkey D. Luffy sails the seas with his crew to find the legendary treasure and become King of the Pirates.",
    rating: 8.7,
    popularity: 91000,
    episodeCount: 1100,
    sourceUrl: "https://anilist.co/anime/21",
    sourceName: "AniList",
    externalId: "21",
  },
  {
    canonicalTitle: "Vinland Saga",
    originalTitle: "ヴィンランド・サガ",
    mediaType: MediaType.ANIME,
    subType: "Seinen",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Historical", "Drama", "Adventure"]),
    description: "A young Viking warrior seeks revenge for his father's death in the brutal world of medieval warfare.",
    rating: 8.8,
    popularity: 76000,
    episodeCount: 48,
    sourceUrl: "https://anilist.co/anime/101348",
    sourceName: "AniList",
    externalId: "101348",
  },
  // Seinen
  {
    canonicalTitle: "Neon Genesis Evangelion",
    originalTitle: "新世紀エヴァンゲリオン",
    mediaType: MediaType.ANIME,
    subType: "Mecha",
    releaseYear: 1995,
    endYear: 1996,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Mecha", "Psychological", "Drama", "Sci-Fi"]),
    description: "Teenagers pilot giant mechs to fight mysterious beings called Angels while grappling with existential despair.",
    rating: 8.5,
    popularity: 78000,
    episodeCount: 26,
    sourceUrl: "https://anilist.co/anime/30",
    sourceName: "AniList",
    externalId: "30",
  },
  {
    canonicalTitle: "Monster",
    originalTitle: "MONSTER",
    mediaType: MediaType.ANIME,
    subType: "Thriller",
    releaseYear: 2004,
    endYear: 2005,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Mystery", "Thriller", "Psychological", "Drama"]),
    description: "A brilliant surgeon discovers the serial killer he once saved has grown into a monster.",
    rating: 8.9,
    popularity: 72000,
    episodeCount: 74,
    sourceUrl: "https://anilist.co/anime/19",
    sourceName: "AniList",
    externalId: "19",
  },
  {
    canonicalTitle: "Berserk",
    originalTitle: "ベルセルク",
    mediaType: MediaType.ANIME,
    subType: "Dark Fantasy",
    releaseYear: 1997,
    endYear: 1998,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Dark Fantasy", "Action", "Drama", "Horror"]),
    description: "A mercenary soldier struggles with his dark destiny alongside a charismatic and terrifying leader.",
    rating: 8.7,
    popularity: 70000,
    episodeCount: 25,
    sourceUrl: "https://anilist.co/anime/33",
    sourceName: "AniList",
    externalId: "33",
  },
  {
    canonicalTitle: "Psycho-Pass",
    originalTitle: "PSYCHO-PASS",
    mediaType: MediaType.ANIME,
    subType: "Cyberpunk",
    releaseYear: 2012,
    endYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Cyberpunk", "Action"]),
    description: "In a future where crime can be predicted, a rookie officer questions the system designed to enforce justice.",
    rating: 8.4,
    popularity: 68000,
    episodeCount: 22,
    sourceUrl: "https://anilist.co/anime/13601",
    sourceName: "AniList",
    externalId: "13601",
  },
  {
    canonicalTitle: "Ghost in the Shell: Stand Alone Complex",
    originalTitle: "攻殻機動隊 STAND ALONE COMPLEX",
    mediaType: MediaType.ANIME,
    subType: "Cyberpunk",
    releaseYear: 2002,
    endYear: 2003,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Cyberpunk", "Thriller", "Action"]),
    description: "A cyborg police officer and her team tackle cybercrime and existential questions in a post-cybernetic world.",
    rating: 8.6,
    popularity: 65000,
    episodeCount: 26,
    sourceUrl: "https://anilist.co/anime/467",
    sourceName: "AniList",
    externalId: "467",
  },
  // Shojo / Romance
  {
    canonicalTitle: "Violet Evergarden",
    originalTitle: "ヴァイオレット・エヴァーガーデン",
    mediaType: MediaType.ANIME,
    subType: "Drama",
    releaseYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Fantasy", "Slice of Life", "Romance"]),
    description: "A former child soldier becomes an Auto Memory Doll, writing letters to help others express their feelings.",
    rating: 8.7,
    popularity: 74000,
    episodeCount: 13,
    sourceUrl: "https://anilist.co/anime/21827",
    sourceName: "AniList",
    externalId: "21827",
  },
  {
    canonicalTitle: "Your Lie in April",
    originalTitle: "四月は君の嘘",
    mediaType: MediaType.ANIME,
    subType: "Romance",
    releaseYear: 2014,
    endYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Music", "Romance", "Drama", "Slice of Life"]),
    description: "A piano prodigy who can no longer hear the music he plays meets a violinist who changes his world.",
    rating: 8.7,
    popularity: 78000,
    episodeCount: 22,
    sourceUrl: "https://anilist.co/anime/20665",
    sourceName: "AniList",
    externalId: "20665",
  },
  {
    canonicalTitle: "Fruits Basket (2019)",
    originalTitle: "フルーツバスケット",
    mediaType: MediaType.ANIME,
    subType: "Shojo",
    releaseYear: 2019,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Romance", "Drama", "Comedy", "Supernatural"]),
    description: "A girl discovers that members of the Sohma family are possessed by spirits of the Chinese zodiac.",
    rating: 8.7,
    popularity: 67000,
    episodeCount: 63,
    sourceUrl: "https://anilist.co/anime/100048",
    sourceName: "AniList",
    externalId: "100048",
  },
  {
    canonicalTitle: "Clannad: After Story",
    originalTitle: "CLANNAD ~AFTER STORY~",
    mediaType: MediaType.ANIME,
    subType: "Romance",
    releaseYear: 2008,
    endYear: 2009,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Romance", "Slice of Life", "Supernatural"]),
    description: "The continuation of Clannad follows Tomoya and Nagisa into their adult lives, family, and hardship.",
    rating: 8.9,
    popularity: 73000,
    episodeCount: 24,
    sourceUrl: "https://anilist.co/anime/4181",
    sourceName: "AniList",
    externalId: "4181",
  },
  {
    canonicalTitle: "Sailor Moon",
    originalTitle: "美少女戦士セーラームーン",
    mediaType: MediaType.ANIME,
    subType: "Magical Girl",
    releaseYear: 1992,
    endYear: 1997,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Magical Girl", "Romance", "Action", "Fantasy"]),
    description: "A clumsy teenage girl transforms into Sailor Moon to defend Earth against evil alongside the Sailor Senshi.",
    rating: 7.7,
    popularity: 62000,
    episodeCount: 200,
    sourceUrl: "https://anilist.co/anime/530",
    sourceName: "AniList",
    externalId: "530",
  },
  // Isekai
  {
    canonicalTitle: "Re:ZERO - Starting Life in Another World",
    originalTitle: "Re:ゼロから始める異世界生活",
    mediaType: MediaType.ANIME,
    subType: "Isekai",
    releaseYear: 2016,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Fantasy", "Psychological", "Drama"]),
    description: "A young man transported to a fantasy world discovers he can return from death — but at great cost.",
    rating: 8.3,
    popularity: 77000,
    episodeCount: 50,
    sourceUrl: "https://anilist.co/anime/21355",
    sourceName: "AniList",
    externalId: "21355",
  },
  {
    canonicalTitle: "Overlord",
    originalTitle: "オーバーロード",
    mediaType: MediaType.ANIME,
    subType: "Isekai",
    releaseYear: 2015,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Dark Fantasy", "Action", "Comedy"]),
    description: "A player becomes trapped in his MMORPG as his character — an undead overlord — and decides to conquer the world.",
    rating: 7.8,
    popularity: 66000,
    episodeCount: 52,
    sourceUrl: "https://anilist.co/anime/20951",
    sourceName: "AniList",
    externalId: "20951",
  },
  {
    canonicalTitle: "KonoSuba: God's Blessing on This Wonderful World!",
    originalTitle: "この素晴らしい世界に祝福を！",
    mediaType: MediaType.ANIME,
    subType: "Isekai",
    releaseYear: 2016,
    endYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Comedy", "Fantasy", "Parody"]),
    description: "A boy dies and is sent to a fantasy world with a useless goddess, building the most dysfunctional adventuring party.",
    rating: 8.1,
    popularity: 71000,
    episodeCount: 20,
    sourceUrl: "https://anilist.co/anime/21202",
    sourceName: "AniList",
    externalId: "21202",
  },
  {
    canonicalTitle: "That Time I Got Reincarnated as a Slime",
    originalTitle: "転生したらスライムだった件",
    mediaType: MediaType.ANIME,
    subType: "Isekai",
    releaseYear: 2018,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Fantasy", "Adventure", "Comedy"]),
    description: "A man reincarnated as a slime monster gains unique powers and builds a nation for monsters.",
    rating: 8.1,
    popularity: 69000,
    episodeCount: 73,
    sourceUrl: "https://anilist.co/anime/101280",
    sourceName: "AniList",
    externalId: "101280",
  },
  // Slice of Life / Comedy
  {
    canonicalTitle: "K-On!",
    originalTitle: "けいおん！",
    mediaType: MediaType.ANIME,
    subType: "Slice of Life",
    releaseYear: 2009,
    endYear: 2010,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Music", "Slice of Life", "Comedy", "School"]),
    description: "Four girls form a high school light music club and discover friendship, music, and cake.",
    rating: 8.1,
    popularity: 62000,
    episodeCount: 26,
    sourceUrl: "https://anilist.co/anime/5680",
    sourceName: "AniList",
    externalId: "5680",
  },
  {
    canonicalTitle: "Nichijou: My Ordinary Life",
    originalTitle: "日常",
    mediaType: MediaType.ANIME,
    subType: "Comedy",
    releaseYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Comedy", "Slice of Life", "School"]),
    description: "An absurdist comedy about the extraordinarily weird daily life of three high school girls.",
    rating: 8.5,
    popularity: 59000,
    episodeCount: 26,
    sourceUrl: "https://anilist.co/anime/10165",
    sourceName: "AniList",
    externalId: "10165",
  },
  {
    canonicalTitle: "Toradora!",
    originalTitle: "とらドラ！",
    mediaType: MediaType.ANIME,
    subType: "Romance",
    releaseYear: 2008,
    endYear: 2009,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Romance", "Comedy", "Slice of Life", "School"]),
    description: "A misunderstood tough-looking boy and a tiny ferocious girl team up to help each other with their crushes.",
    rating: 8.2,
    popularity: 72000,
    episodeCount: 25,
    sourceUrl: "https://anilist.co/anime/4224",
    sourceName: "AniList",
    externalId: "4224",
  },
  // Sci-Fi / Mecha
  {
    canonicalTitle: "Gurren Lagann",
    originalTitle: "天元突破グレンラガン",
    mediaType: MediaType.ANIME,
    subType: "Mecha",
    releaseYear: 2007,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Mecha", "Action", "Adventure", "Sci-Fi"]),
    description: "Two brothers discover a mecha and fight to lead humanity from underground to the stars.",
    rating: 8.7,
    popularity: 76000,
    episodeCount: 27,
    sourceUrl: "https://anilist.co/anime/2001",
    sourceName: "AniList",
    externalId: "2001",
  },
  {
    canonicalTitle: "Code Geass: Lelouch of the Rebellion",
    originalTitle: "コードギアス 反逆のルルーシュ",
    mediaType: MediaType.ANIME,
    subType: "Mecha",
    releaseYear: 2006,
    endYear: 2007,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Mecha", "Action", "Thriller", "Sci-Fi"]),
    description: "An exiled prince gains the power to command anyone to do anything and uses it to lead a rebellion.",
    rating: 8.7,
    popularity: 79000,
    episodeCount: 25,
    sourceUrl: "https://anilist.co/anime/1575",
    sourceName: "AniList",
    externalId: "1575",
  },
  // Sports
  {
    canonicalTitle: "Haikyuu!!",
    originalTitle: "ハイキュー!!",
    mediaType: MediaType.ANIME,
    subType: "Sports",
    releaseYear: 2014,
    endYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sports", "Drama", "Comedy", "School"]),
    description: "A short boy with an enormous love for volleyball fights his way to the top of high school volleyball.",
    rating: 8.7,
    popularity: 80000,
    episodeCount: 85,
    sourceUrl: "https://anilist.co/anime/20583",
    sourceName: "AniList",
    externalId: "20583",
  },
  {
    canonicalTitle: "Yuri!!! on Ice",
    originalTitle: "ユーリ!!! on ICE",
    mediaType: MediaType.ANIME,
    subType: "Sports",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sports", "Romance", "Drama"]),
    description: "A figure skater's comeback story as he trains under his idol and discovers new sides of himself.",
    rating: 8.2,
    popularity: 64000,
    episodeCount: 12,
    sourceUrl: "https://anilist.co/anime/21699",
    sourceName: "AniList",
    externalId: "21699",
  },
  // Classic / Film
  {
    canonicalTitle: "Akira",
    originalTitle: "AKIRA",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1988,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Cyberpunk", "Sci-Fi", "Action", "Psychological"]),
    description: "In a dystopian Neo-Tokyo, a biker's friend unleashes psychic powers that could destroy the city.",
    rating: 8.2,
    popularity: 75000,
    duration: 124,
    sourceUrl: "https://anilist.co/anime/47",
    sourceName: "AniList",
    externalId: "47",
  },
  {
    canonicalTitle: "Ghost in the Shell",
    originalTitle: "攻殻機動隊",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1995,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Cyberpunk", "Sci-Fi", "Action", "Philosophical"]),
    description: "A cyborg police officer hunts a mysterious hacker while questioning her own humanity.",
    rating: 8.3,
    popularity: 69000,
    duration: 83,
    sourceUrl: "https://anilist.co/anime/43",
    sourceName: "AniList",
    externalId: "43",
  },
  {
    canonicalTitle: "Perfect Blue",
    originalTitle: "パーフェクトブルー",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1997,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Psychological", "Thriller", "Horror", "Drama"]),
    description: "A pop idol transitions to acting but is stalked by an obsessive fan and haunted by her former identity.",
    rating: 8.5,
    popularity: 66000,
    duration: 81,
    sourceUrl: "https://anilist.co/anime/44",
    sourceName: "AniList",
    externalId: "44",
  },
  {
    canonicalTitle: "Millennium Actress",
    originalTitle: "千年女優",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2001,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Romance", "Historical", "Mystery"]),
    description: "A documentary filmmaker interviews a legendary actress whose life story blurs with her film roles.",
    rating: 8.4,
    popularity: 52000,
    duration: 87,
    sourceUrl: "https://anilist.co/anime/48",
    sourceName: "AniList",
    externalId: "48",
  },
  // Continuing popular shows
  {
    canonicalTitle: "Chainsaw Man",
    originalTitle: "チェンソーマン",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2022,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Dark Fantasy", "Horror", "Comedy"]),
    description: "A poor young man fuses with his devil dog to become Chainsaw Man and join a devil-hunting agency.",
    rating: 8.5,
    popularity: 83000,
    episodeCount: 12,
    sourceUrl: "https://anilist.co/anime/127230",
    sourceName: "AniList",
    externalId: "127230",
  },
  {
    canonicalTitle: "Spy x Family",
    originalTitle: "SPY×FAMILY",
    mediaType: MediaType.ANIME,
    subType: "Comedy",
    releaseYear: 2022,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Comedy", "Action", "Slice of Life", "Spy"]),
    description: "A spy, an assassin, and a telepathic child form a fake family — none of them knowing the others' secrets.",
    rating: 8.6,
    popularity: 79000,
    episodeCount: 37,
    sourceUrl: "https://anilist.co/anime/140960",
    sourceName: "AniList",
    externalId: "140960",
  },
  {
    canonicalTitle: "Frieren: Beyond Journey's End",
    originalTitle: "葬送のフリーレン",
    mediaType: MediaType.ANIME,
    subType: "Fantasy",
    releaseYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Slice of Life", "Drama"]),
    description: "An elven mage who barely noticed time passing must now grapple with mortality and what it means to know someone.",
    rating: 9.0,
    popularity: 85000,
    episodeCount: 28,
    sourceUrl: "https://anilist.co/anime/154587",
    sourceName: "AniList",
    externalId: "154587",
  },
  {
    canonicalTitle: "Mob Psycho 100",
    originalTitle: "モブサイコ100",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2016,
    endYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Comedy", "Supernatural", "Slice of Life"]),
    description: "An incredibly powerful psychic boy tries to live a normal life while working for a con-artist exorcist.",
    rating: 8.8,
    popularity: 77000,
    episodeCount: 37,
    sourceUrl: "https://anilist.co/anime/21507",
    sourceName: "AniList",
    externalId: "21507",
  },
  {
    canonicalTitle: "Made in Abyss",
    originalTitle: "メイドインアビス",
    mediaType: MediaType.ANIME,
    subType: "Adventure",
    releaseYear: 2017,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Adventure", "Fantasy", "Dark Fantasy", "Drama"]),
    description: "A girl and her robot friend descend into a vast, mysterious, and deadly abyss in search of her missing mother.",
    rating: 8.7,
    popularity: 72000,
    episodeCount: 25,
    sourceUrl: "https://anilist.co/anime/97986",
    sourceName: "AniList",
    externalId: "97986",
  },
  {
    canonicalTitle: "Steins;Gate",
    originalTitle: "シュタインズ・ゲート",
    mediaType: MediaType.ANIME,
    subType: "Sci-Fi",
    releaseYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Drama", "Time Travel"]),
    description: "A self-proclaimed mad scientist accidentally invents time travel via microwave, with catastrophic consequences.",
    rating: 9.1,
    popularity: 86000,
    episodeCount: 24,
    sourceUrl: "https://anilist.co/anime/9253",
    sourceName: "AniList",
    externalId: "9253",
  },
  {
    canonicalTitle: "Death Note",
    originalTitle: "デスノート",
    mediaType: MediaType.ANIME,
    subType: "Thriller",
    releaseYear: 2006,
    endYear: 2007,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Psychological", "Thriller", "Supernatural", "Drama"]),
    description: "A genius student finds a supernatural notebook that kills anyone whose name is written in it.",
    rating: 8.6,
    popularity: 90000,
    episodeCount: 37,
    sourceUrl: "https://anilist.co/anime/1535",
    sourceName: "AniList",
    externalId: "1535",
  },
  {
    canonicalTitle: "Cowboy Bebop",
    originalTitle: "カウボーイビバップ",
    mediaType: MediaType.ANIME,
    subType: "Space Western",
    releaseYear: 1998,
    endYear: 1999,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Action", "Drama", "Jazz"]),
    description: "A ragtag crew of bounty hunters drift through the solar system, each haunted by their pasts.",
    rating: 8.9,
    popularity: 82000,
    episodeCount: 26,
    sourceUrl: "https://anilist.co/anime/1",
    sourceName: "AniList",
    externalId: "1",
  },
  {
    canonicalTitle: "Fullmetal Alchemist (2003)",
    originalTitle: "鋼の錬金術師",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2003,
    endYear: 2004,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy", "Drama"]),
    description: "The original 2003 adaptation of Fullmetal Alchemist with its own unique darker storyline.",
    rating: 8.1,
    popularity: 68000,
    episodeCount: 51,
    sourceUrl: "https://anilist.co/anime/121",
    sourceName: "AniList",
    externalId: "121",
  },
  {
    canonicalTitle: "Blue Exorcist",
    originalTitle: "青の祓魔師",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2011,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Supernatural", "Fantasy", "School"]),
    description: "The son of Satan enrolls in a demon-slaying academy to become an exorcist and defeat his own father.",
    rating: 7.7,
    popularity: 59000,
    episodeCount: 25,
    sourceUrl: "https://anilist.co/anime/9919",
    sourceName: "AniList",
    externalId: "9919",
  },
  {
    canonicalTitle: "Naruto",
    originalTitle: "ナルト",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2002,
    endYear: 2007,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy", "Martial Arts"]),
    description: "A young ninja with a demon fox spirit inside him dreams of becoming the greatest ninja in his village.",
    rating: 7.9,
    popularity: 85000,
    episodeCount: 220,
    sourceUrl: "https://anilist.co/anime/20",
    sourceName: "AniList",
    externalId: "20",
  },
  {
    canonicalTitle: "Sword Art Online",
    originalTitle: "ソードアート・オンライン",
    mediaType: MediaType.ANIME,
    subType: "Isekai",
    releaseYear: 2012,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Action", "Adventure", "Romance"]),
    description: "Players become trapped in a virtual reality MMORPG where death in the game means death in real life.",
    rating: 7.2,
    popularity: 80000,
    episodeCount: 25,
    sourceUrl: "https://anilist.co/anime/11757",
    sourceName: "AniList",
    externalId: "11757",
  },
  {
    canonicalTitle: "Cardcaptor Sakura",
    originalTitle: "カードキャプターさくら",
    mediaType: MediaType.ANIME,
    subType: "Magical Girl",
    releaseYear: 1998,
    endYear: 2000,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Magical Girl", "Fantasy", "Romance", "Adventure"]),
    description: "A fourth-grader accidentally releases magical cards and must capture them all with her new guardian beast.",
    rating: 8.3,
    popularity: 60000,
    episodeCount: 70,
    sourceUrl: "https://anilist.co/anime/232",
    sourceName: "AniList",
    externalId: "232",
  },
  {
    canonicalTitle: "Hajime no Ippo",
    originalTitle: "はじめの一歩",
    mediaType: MediaType.ANIME,
    subType: "Sports",
    releaseYear: 2000,
    endYear: 2002,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sports", "Drama", "Comedy", "Action"]),
    description: "A timid high school boy discovers a natural talent for boxing and fights his way to the top.",
    rating: 8.7,
    popularity: 62000,
    episodeCount: 75,
    sourceUrl: "https://anilist.co/anime/263",
    sourceName: "AniList",
    externalId: "263",
  },
  {
    canonicalTitle: "Black Clover",
    originalTitle: "ブラッククローバー",
    mediaType: MediaType.ANIME,
    subType: "Shonen",
    releaseYear: 2017,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Fantasy", "Adventure", "Magic"]),
    description: "A boy born without magic in a world of magic vows to become the Wizard King through sheer determination.",
    rating: 7.6,
    popularity: 62000,
    episodeCount: 170,
    sourceUrl: "https://anilist.co/anime/97940",
    sourceName: "AniList",
    externalId: "97940",
  },
  {
    canonicalTitle: "Puella Magi Madoka Magica",
    originalTitle: "魔法少女まどか☆マギカ",
    mediaType: MediaType.ANIME,
    subType: "Magical Girl",
    releaseYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Magical Girl", "Psychological", "Drama", "Dark Fantasy"]),
    description: "Middle schoolers are offered a chance to become magical girls — but the cost is far darker than it seems.",
    rating: 8.6,
    popularity: 77000,
    episodeCount: 12,
    sourceUrl: "https://anilist.co/anime/9756",
    sourceName: "AniList",
    externalId: "9756",
  },
  {
    canonicalTitle: "Samurai Champloo",
    originalTitle: "サムライチャンプルー",
    mediaType: MediaType.ANIME,
    subType: "Samurai",
    releaseYear: 2004,
    endYear: 2005,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Historical", "Adventure", "Hip-Hop"]),
    description: "Two swordsmen with opposing styles and a girl searching for a mysterious samurai journey through Edo-period Japan.",
    rating: 8.5,
    popularity: 68000,
    episodeCount: 26,
    sourceUrl: "https://anilist.co/anime/205",
    sourceName: "AniList",
    externalId: "205",
  },
  {
    canonicalTitle: "Nana",
    originalTitle: "NANA",
    mediaType: MediaType.ANIME,
    subType: "Josei",
    releaseYear: 2006,
    endYear: 2007,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Romance", "Music", "Slice of Life"]),
    description: "Two women named Nana meet on a train to Tokyo and become unlikely roommates and best friends.",
    rating: 8.5,
    popularity: 61000,
    episodeCount: 47,
    sourceUrl: "https://anilist.co/anime/877",
    sourceName: "AniList",
    externalId: "877",
  },
  {
    canonicalTitle: "Parasyte: The Maxim",
    originalTitle: "寄生獣 セイの格率",
    mediaType: MediaType.ANIME,
    subType: "Sci-Fi",
    releaseYear: 2014,
    endYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Horror", "Action", "Psychological"]),
    description: "A parasite fails to reach a boy's brain and instead bonds with his hand, forcing an uneasy coexistence.",
    rating: 8.5,
    popularity: 74000,
    episodeCount: 24,
    sourceUrl: "https://anilist.co/anime/22535",
    sourceName: "AniList",
    externalId: "22535",
  },
  {
    canonicalTitle: "A Silent Voice",
    originalTitle: "聲の形",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Romance", "School"]),
    description: "A former bully seeks to make amends with the deaf girl he once tormented, exploring guilt, forgiveness, and connection.",
    rating: 8.9,
    popularity: 78000,
    duration: 130,
    sourceUrl: "https://anilist.co/anime/20954",
    sourceName: "AniList",
    externalId: "20954",
  },
  {
    canonicalTitle: "Your Name",
    originalTitle: "君の名は。",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Romance", "Fantasy", "Drama"]),
    description: "A boy and a girl who have never met begin switching bodies and develop an inexplicable connection.",
    rating: 8.9,
    popularity: 88000,
    duration: 112,
    sourceUrl: "https://anilist.co/anime/21519",
    sourceName: "AniList",
    externalId: "21519",
  },
  {
    canonicalTitle: "Paprika",
    originalTitle: "パプリカ",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2006,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Psychological", "Fantasy", "Thriller"]),
    description: "A psychotherapist uses a device that allows therapists to enter patients' dreams, but it is stolen.",
    rating: 8.3,
    popularity: 63000,
    duration: 90,
    sourceUrl: "https://anilist.co/anime/1291",
    sourceName: "AniList",
    externalId: "1291",
  },
] as const;
