import { MediaType, MediaStatus } from "@prisma/client";

export const animationTitles = [
  {
    canonicalTitle: "Batman: The Animated Series",
    originalTitle: "Batman: The Animated Series",
    mediaType: MediaType.ANIMATION,
    subType: "Superhero",
    releaseYear: 1992,
    endYear: 1995,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Action", "Crime", "Drama"]),
    description: "The definitive animated Batman adaptation — dark, stylish, and featuring iconic villain portrayals.",
    rating: 9.0,
    popularity: 75000,
    episodeCount: 85,
    sourceUrl: "https://www.themoviedb.org/tv/2085",
    sourceName: "TMDB",
    externalId: "anim-2085",
  },
  {
    canonicalTitle: "Avatar: The Last Airbender",
    originalTitle: "Avatar: The Last Airbender",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2005,
    endYear: 2008,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Action", "Drama"]),
    description: "A young boy is the Avatar, the only one who can master all four elements and stop a global war.",
    rating: 9.3,
    popularity: 88000,
    episodeCount: 61,
    sourceUrl: "https://www.themoviedb.org/tv/246",
    sourceName: "TMDB",
    externalId: "anim-246",
  },
  {
    canonicalTitle: "Gravity Falls",
    originalTitle: "Gravity Falls",
    mediaType: MediaType.ANIMATION,
    subType: "Mystery",
    releaseYear: 2012,
    endYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Mystery", "Comedy", "Fantasy", "Adventure"]),
    description: "Twin siblings spend a summer in a mysterious Oregon town with their conspiracy-theorist great-uncle.",
    rating: 8.9,
    popularity: 82000,
    episodeCount: 40,
    sourceUrl: "https://www.themoviedb.org/tv/40075",
    sourceName: "TMDB",
    externalId: "anim-40075",
  },
  {
    canonicalTitle: "Arcane",
    originalTitle: "Arcane",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2021,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Action", "Drama", "Steampunk"]),
    description: "The origins of two iconic League of Legends characters in the separated cities of Piltover and Zaun.",
    rating: 9.0,
    popularity: 86000,
    episodeCount: 18,
    sourceUrl: "https://www.themoviedb.org/tv/94954",
    sourceName: "TMDB",
    externalId: "anim-94954",
  },
  {
    canonicalTitle: "Castlevania",
    originalTitle: "Castlevania",
    mediaType: MediaType.ANIMATION,
    subType: "Dark Fantasy",
    releaseYear: 2017,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Dark Fantasy", "Action", "Horror", "Adventure"]),
    description: "Vlad Dracula Tepes wages war on Wallachia after his wife is burned at the stake for witchcraft.",
    rating: 8.3,
    popularity: 74000,
    episodeCount: 32,
    sourceUrl: "https://www.themoviedb.org/tv/71728",
    sourceName: "TMDB",
    externalId: "anim-71728",
  },
  {
    canonicalTitle: "Samurai Jack",
    originalTitle: "Samurai Jack",
    mediaType: MediaType.ANIMATION,
    subType: "Action",
    releaseYear: 2001,
    endYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Action", "Adventure", "Sci-Fi", "Fantasy"]),
    description: "A time-displaced samurai prince battles the shape-shifting demon Aku through a futuristic dystopia.",
    rating: 8.6,
    popularity: 68000,
    episodeCount: 62,
    sourceUrl: "https://www.themoviedb.org/tv/2296",
    sourceName: "TMDB",
    externalId: "anim-2296",
  },
  {
    canonicalTitle: "Primal",
    originalTitle: "Primal",
    mediaType: MediaType.ANIMATION,
    subType: "Action",
    releaseYear: 2019,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Action", "Adventure", "Drama"]),
    description: "A caveman and a dinosaur form a bond while surviving a brutal prehistoric world — told without dialogue.",
    rating: 8.8,
    popularity: 66000,
    episodeCount: 20,
    sourceUrl: "https://www.themoviedb.org/tv/90462",
    sourceName: "TMDB",
    externalId: "anim-90462",
  },
  {
    canonicalTitle: "The Legend of Korra",
    originalTitle: "The Legend of Korra",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2012,
    endYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Action", "Adventure", "Drama"]),
    description: "The successor to Avatar must master all four elements and navigate a modernizing world.",
    rating: 8.4,
    popularity: 74000,
    episodeCount: 52,
    sourceUrl: "https://www.themoviedb.org/tv/40707",
    sourceName: "TMDB",
    externalId: "anim-40707",
  },
  {
    canonicalTitle: "Steven Universe",
    originalTitle: "Steven Universe",
    mediaType: MediaType.ANIMATION,
    subType: "Magical",
    releaseYear: 2013,
    endYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Comedy", "Musical"]),
    description: "A boy with a magical gem in his belly button helps his family of Crystal Gems protect the Earth.",
    rating: 8.2,
    popularity: 70000,
    episodeCount: 160,
    sourceUrl: "https://www.themoviedb.org/tv/41075",
    sourceName: "TMDB",
    externalId: "anim-41075",
  },
  {
    canonicalTitle: "Invincible",
    originalTitle: "Invincible",
    mediaType: MediaType.ANIMATION,
    subType: "Superhero",
    releaseYear: 2021,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Action", "Drama", "Mature"]),
    description: "A teenager discovers his father is the world's most powerful superhero — and something terrifying.",
    rating: 8.7,
    popularity: 80000,
    episodeCount: 16,
    sourceUrl: "https://www.themoviedb.org/tv/95557",
    sourceName: "TMDB",
    externalId: "anim-95557",
  },
  {
    canonicalTitle: "Justice League Unlimited",
    originalTitle: "Justice League Unlimited",
    mediaType: MediaType.ANIMATION,
    subType: "Superhero",
    releaseYear: 2004,
    endYear: 2006,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Action", "Adventure"]),
    description: "An expanded roster of DC heroes tackles threats too large for any individual hero.",
    rating: 8.7,
    popularity: 62000,
    episodeCount: 39,
    sourceUrl: "https://www.themoviedb.org/tv/24313",
    sourceName: "TMDB",
    externalId: "anim-24313",
  },
  {
    canonicalTitle: "The Owl House",
    originalTitle: "The Owl House",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2020,
    endYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Comedy", "LGBTQ+"]),
    description: "A girl accidentally stumbles into the Boiling Isles, a realm of demons and witches, and finds her calling.",
    rating: 8.5,
    popularity: 68000,
    episodeCount: 40,
    sourceUrl: "https://www.themoviedb.org/tv/89175",
    sourceName: "TMDB",
    externalId: "anim-89175",
  },
  {
    canonicalTitle: "Amphibia",
    originalTitle: "Amphibia",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2019,
    endYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Comedy"]),
    description: "A self-centered girl is transported to a world of amphibians and must learn to grow and find her way home.",
    rating: 8.1,
    popularity: 58000,
    episodeCount: 57,
    sourceUrl: "https://www.themoviedb.org/tv/85255",
    sourceName: "TMDB",
    externalId: "anim-85255",
  },
  {
    canonicalTitle: "She-Ra and the Princesses of Power",
    originalTitle: "She-Ra and the Princesses of Power",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2018,
    endYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Action", "Adventure", "LGBTQ+"]),
    description: "A girl discovers she is the legendary princess She-Ra and must lead a rebellion against the Horde.",
    rating: 8.1,
    popularity: 64000,
    episodeCount: 52,
    sourceUrl: "https://www.themoviedb.org/tv/75219",
    sourceName: "TMDB",
    externalId: "anim-75219",
  },
  {
    canonicalTitle: "Infinity Train",
    originalTitle: "Infinity Train",
    mediaType: MediaType.ANIMATION,
    subType: "Sci-Fi",
    releaseYear: 2019,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Fantasy", "Mystery", "Drama"]),
    description: "People wake up on a mysterious infinite train with a number on their hand — each must solve their car to leave.",
    rating: 8.7,
    popularity: 60000,
    episodeCount: 40,
    sourceUrl: "https://www.themoviedb.org/tv/92136",
    sourceName: "TMDB",
    externalId: "anim-92136",
  },
  {
    canonicalTitle: "Gargoyles",
    originalTitle: "Gargoyles",
    mediaType: MediaType.ANIMATION,
    subType: "Action",
    releaseYear: 1994,
    endYear: 1996,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Action", "Fantasy", "Drama", "Mystery"]),
    description: "Mythical gargoyle warriors are magically frozen in stone, then reawakened in modern Manhattan.",
    rating: 8.3,
    popularity: 56000,
    episodeCount: 78,
    sourceUrl: "https://www.themoviedb.org/tv/4926",
    sourceName: "TMDB",
    externalId: "anim-4926",
  },
  {
    canonicalTitle: "Star Wars: The Clone Wars",
    originalTitle: "Star Wars: The Clone Wars",
    mediaType: MediaType.ANIMATION,
    subType: "Sci-Fi",
    releaseYear: 2008,
    endYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Action", "Adventure", "War"]),
    description: "Jedi and clone troopers fight in the conflict between the Republic and the Separatists between Episodes II and III.",
    rating: 8.5,
    popularity: 72000,
    episodeCount: 133,
    sourceUrl: "https://www.themoviedb.org/tv/4194",
    sourceName: "TMDB",
    externalId: "anim-4194",
  },
  {
    canonicalTitle: "Hilda",
    originalTitle: "Hilda",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2018,
    endYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Comedy", "Family"]),
    description: "A fearless blue-haired girl moves from the wilderness to a city teeming with trolls, elves, and spirits.",
    rating: 8.5,
    popularity: 58000,
    episodeCount: 39,
    sourceUrl: "https://www.themoviedb.org/tv/79362",
    sourceName: "TMDB",
    externalId: "anim-79362",
  },
  {
    canonicalTitle: "The Dragon Prince",
    originalTitle: "The Dragon Prince",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2018,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Drama"]),
    description: "Two princes and an elf assassin forge an unlikely alliance to bring peace to their kingdoms.",
    rating: 8.2,
    popularity: 62000,
    episodeCount: 72,
    sourceUrl: "https://www.themoviedb.org/tv/76331",
    sourceName: "TMDB",
    externalId: "anim-76331",
  },
  {
    canonicalTitle: "Kipo and the Age of Wonderbeasts",
    originalTitle: "Kipo and the Age of Wonderbeasts",
    mediaType: MediaType.ANIMATION,
    subType: "Sci-Fi",
    releaseYear: 2020,
    endYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Adventure", "Fantasy", "Music"]),
    description: "A girl who grew up underground must navigate the post-apocalyptic surface world full of mutant animals.",
    rating: 8.1,
    popularity: 50000,
    episodeCount: 30,
    sourceUrl: "https://www.themoviedb.org/tv/83744",
    sourceName: "TMDB",
    externalId: "anim-83744",
  },
  {
    canonicalTitle: "Bee and Puppycat",
    originalTitle: "Bee and PuppyCat",
    mediaType: MediaType.ANIMATION,
    subType: "Slice of Life",
    releaseYear: 2013,
    endYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Slice of Life", "Comedy", "Magical"]),
    description: "A young woman and her mysterious animal companion take temp jobs for an alien employment agency.",
    rating: 7.7,
    popularity: 44000,
    episodeCount: 23,
    sourceUrl: "https://www.themoviedb.org/tv/59975",
    sourceName: "TMDB",
    externalId: "anim-59975",
  },
  {
    canonicalTitle: "X-Men: The Animated Series",
    originalTitle: "X-Men: The Animated Series",
    mediaType: MediaType.ANIMATION,
    subType: "Superhero",
    releaseYear: 1992,
    endYear: 1997,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Action", "Drama", "Social Commentary"]),
    description: "Marvel's X-Men fight for mutant rights and save a world that hates and fears them.",
    rating: 8.4,
    popularity: 66000,
    episodeCount: 76,
    sourceUrl: "https://www.themoviedb.org/tv/1411",
    sourceName: "TMDB",
    externalId: "anim-1411",
  },
  {
    canonicalTitle: "Sym-Bionic Titan",
    originalTitle: "Sym-Bionic Titan",
    mediaType: MediaType.ANIMATION,
    subType: "Mecha",
    releaseYear: 2010,
    endYear: 2011,
    status: MediaStatus.CANCELLED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Mecha", "Action", "Sci-Fi", "High School"]),
    description: "Two aliens and a robot disguised as humans defend Earth from an evil general who destroyed their planet.",
    rating: 8.4,
    popularity: 42000,
    episodeCount: 20,
    sourceUrl: "https://www.themoviedb.org/tv/40001",
    sourceName: "TMDB",
    externalId: "anim-40001",
  },
  {
    canonicalTitle: "Murder Drones",
    originalTitle: "Murder Drones",
    mediaType: MediaType.ANIMATION,
    subType: "Sci-Fi",
    releaseYear: 2023,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Dark Comedy", "Action", "Horror"]),
    description: "Worker drones scrape by on a desolate planet while avoiding the Disassembly Drones sent to eliminate them.",
    rating: 8.3,
    popularity: 52000,
    episodeCount: 9,
    sourceUrl: "https://www.themoviedb.org/tv/216283",
    sourceName: "TMDB",
    externalId: "anim-216283",
  },
  {
    canonicalTitle: "Disenchantment",
    originalTitle: "Disenchantment",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2018,
    endYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Comedy", "Adventure", "Adult"]),
    description: "A hard-drinking princess, her elf companion, and a personal demon go on misadventures in the kingdom of Dreamland.",
    rating: 7.4,
    popularity: 62000,
    episodeCount: 52,
    sourceUrl: "https://www.themoviedb.org/tv/75006",
    sourceName: "TMDB",
    externalId: "anim-75006",
  },
  {
    canonicalTitle: "Wakfu",
    originalTitle: "Wakfu",
    mediaType: MediaType.ANIMATION,
    subType: "Fantasy",
    releaseYear: 2008,
    status: MediaStatus.ONGOING,
    country: "FR",
    language: "fr",
    genres: JSON.stringify(["Fantasy", "Adventure", "Action", "Comedy"]),
    description: "A young boy with immense power embarks on a quest to find his origins in a world of magic and adventure.",
    rating: 8.4,
    popularity: 48000,
    episodeCount: 66,
    sourceUrl: "https://www.themoviedb.org/tv/23507",
    sourceName: "TMDB",
    externalId: "anim-23507",
  },
  {
    canonicalTitle: "Inside Job",
    originalTitle: "Inside Job",
    mediaType: MediaType.ANIMATION,
    subType: "Comedy",
    releaseYear: 2021,
    endYear: 2022,
    status: MediaStatus.CANCELLED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Comedy", "Sci-Fi", "Adult", "Conspiracy"]),
    description: "A socially awkward genius works at the deep state organization responsible for all the world's conspiracies.",
    rating: 8.0,
    popularity: 55000,
    episodeCount: 18,
    sourceUrl: "https://www.themoviedb.org/tv/122695",
    sourceName: "TMDB",
    externalId: "anim-122695",
  },
] as const;
