import { MediaType, MediaStatus } from "@prisma/client";

export const bookTitles = [
  {
    canonicalTitle: "Dune",
    originalTitle: "Dune",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1965,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Epic", "Political", "Ecological"]),
    description: "A noble boy is thrust into the politics and ecology of a desert planet that produces the universe's most precious substance.",
    rating: 8.9,
    popularity: 88000,
    sourceUrl: "https://openlibrary.org/works/OL36079W",
    sourceName: "Open Library",
    externalId: "ol-dune",
  },
  {
    canonicalTitle: "The Left Hand of Darkness",
    originalTitle: "The Left Hand of Darkness",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1969,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Political", "Gender", "Anthropology"]),
    description: "An envoy visits a world where humans have no fixed gender, exploring culture, politics, and difference.",
    rating: 8.7,
    popularity: 62000,
    sourceUrl: "https://openlibrary.org/works/OL59706W",
    sourceName: "Open Library",
    externalId: "ol-left-hand",
  },
  {
    canonicalTitle: "Neuromancer",
    originalTitle: "Neuromancer",
    mediaType: MediaType.NOVEL,
    subType: "Cyberpunk",
    releaseYear: 1984,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Cyberpunk", "Sci-Fi", "Thriller", "Noir"]),
    description: "A burned-out hacker is hired for one last job — to penetrate the most sophisticated AI ever built.",
    rating: 8.4,
    popularity: 70000,
    sourceUrl: "https://openlibrary.org/works/OL27516W",
    sourceName: "Open Library",
    externalId: "ol-neuromancer",
  },
  {
    canonicalTitle: "Hyperion",
    originalTitle: "Hyperion",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1989,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Epic", "Literary"]),
    description: "Seven pilgrims on a doomed journey share their stories — each a different genre of science fiction.",
    rating: 8.9,
    popularity: 72000,
    sourceUrl: "https://openlibrary.org/works/OL20632370W",
    sourceName: "Open Library",
    externalId: "ol-hyperion",
  },
  {
    canonicalTitle: "Ender's Game",
    originalTitle: "Ender's Game",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1985,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Military", "Drama", "War"]),
    description: "A gifted child is trained in a space academy to become the commander who saves humanity from alien invaders.",
    rating: 8.5,
    popularity: 76000,
    sourceUrl: "https://openlibrary.org/works/OL460934W",
    sourceName: "Open Library",
    externalId: "ol-enders-game",
  },
  {
    canonicalTitle: "Solaris",
    originalTitle: "Solaris",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1961,
    status: MediaStatus.COMPLETED,
    country: "PL",
    language: "pl",
    genres: JSON.stringify(["Sci-Fi", "Philosophical", "Psychological"]),
    description: "Scientists studying a sentient ocean on a distant planet find it projecting their deepest psychological constructs.",
    rating: 8.5,
    popularity: 58000,
    sourceUrl: "https://openlibrary.org/works/OL7990W",
    sourceName: "Open Library",
    externalId: "ol-solaris",
  },
  {
    canonicalTitle: "Roadside Picnic",
    originalTitle: "Пикник на обочине",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1972,
    status: MediaStatus.COMPLETED,
    country: "RU",
    language: "ru",
    genres: JSON.stringify(["Sci-Fi", "Philosophical", "Post-Contact"]),
    description: "Scavengers enter alien-visited Zones to retrieve dangerous artifacts in a world forever changed by extraterrestrial visitors.",
    rating: 8.7,
    popularity: 55000,
    sourceUrl: "https://openlibrary.org/works/OL4316166W",
    sourceName: "Open Library",
    externalId: "ol-roadside",
  },
  {
    canonicalTitle: "Never Let Me Go",
    originalTitle: "Never Let Me Go",
    mediaType: MediaType.NOVEL,
    subType: "Dystopia",
    releaseYear: 2005,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Literary Fiction", "Dystopia", "Sci-Fi", "Drama"]),
    description: "Former students of a boarding school discover their true purpose — a future that is both mundane and devastating.",
    rating: 8.4,
    popularity: 60000,
    sourceUrl: "https://openlibrary.org/works/OL2631446W",
    sourceName: "Open Library",
    externalId: "ol-never-let-me-go",
  },
  {
    canonicalTitle: "The Stars My Destination",
    originalTitle: "The Stars My Destination",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1956,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Revenge", "Action", "Literary"]),
    description: "A man abandoned in space seeks brutal revenge against those who left him to die in a future where teleportation is universal.",
    rating: 8.6,
    popularity: 50000,
    sourceUrl: "https://openlibrary.org/works/OL1963W",
    sourceName: "Open Library",
    externalId: "ol-stars-destination",
  },
  {
    canonicalTitle: "The Dispossessed",
    originalTitle: "The Dispossessed",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1974,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Anarchism", "Political", "Philosophical"]),
    description: "A physicist from a utopian anarchist society travels to its twin capitalist world and challenges both systems.",
    rating: 8.6,
    popularity: 54000,
    sourceUrl: "https://openlibrary.org/works/OL59709W",
    sourceName: "Open Library",
    externalId: "ol-dispossessed",
  },
  {
    canonicalTitle: "Spice and Wolf",
    originalTitle: "狼と香辛料",
    mediaType: MediaType.LIGHT_NOVEL,
    subType: "Fantasy",
    releaseYear: 2006,
    endYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Romance", "Economics", "Adventure"]),
    description: "A traveling merchant and an ancient wolf deity journey together through a medieval landscape, discussing trade and life.",
    rating: 8.6,
    popularity: 68000,
    sourceUrl: "https://anilist.co/manga/39115",
    sourceName: "AniList",
    externalId: "ln-39115",
  },
  {
    canonicalTitle: "Overlord",
    originalTitle: "オーバーロード",
    mediaType: MediaType.LIGHT_NOVEL,
    subType: "Isekai",
    releaseYear: 2012,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Dark Fantasy", "Action", "Comedy"]),
    description: "The light novel that spawned the anime — a player trapped in his MMORPG as an undead overlord.",
    rating: 8.4,
    popularity: 62000,
    sourceUrl: "https://anilist.co/manga/85470",
    sourceName: "AniList",
    externalId: "ln-85470",
  },
  {
    canonicalTitle: "Re:ZERO - Starting Life in Another World",
    originalTitle: "Re:ゼロから始める異世界生活",
    mediaType: MediaType.LIGHT_NOVEL,
    subType: "Isekai",
    releaseYear: 2014,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Fantasy", "Psychological", "Drama"]),
    description: "The source light novel for the beloved anime — a boy who returns from death in a fantasy world.",
    rating: 8.5,
    popularity: 65000,
    sourceUrl: "https://anilist.co/manga/97414",
    sourceName: "AniList",
    externalId: "ln-97414",
  },
  {
    canonicalTitle: "Ascendance of a Bookworm",
    originalTitle: "本好きの下剋上",
    mediaType: MediaType.LIGHT_NOVEL,
    subType: "Isekai",
    releaseYear: 2015,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Fantasy", "Slice of Life", "Books"]),
    description: "A bookworm reincarnated in a low-literacy medieval world resolves to make books by any means necessary.",
    rating: 8.7,
    popularity: 55000,
    sourceUrl: "https://anilist.co/manga/104514",
    sourceName: "AniList",
    externalId: "ln-104514",
  },
  {
    canonicalTitle: "Mushoku Tensei: Jobless Reincarnation",
    originalTitle: "無職転生",
    mediaType: MediaType.LIGHT_NOVEL,
    subType: "Isekai",
    releaseYear: 2012,
    endYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Fantasy", "Adventure", "Magic"]),
    description: "A shut-in reincarnates in a fantasy world and resolves to live life without regrets.",
    rating: 8.3,
    popularity: 70000,
    sourceUrl: "https://anilist.co/manga/85564",
    sourceName: "AniList",
    externalId: "ln-85564",
  },
  {
    canonicalTitle: "No Game No Life",
    originalTitle: "ノーゲーム・ノーライフ",
    mediaType: MediaType.LIGHT_NOVEL,
    subType: "Isekai",
    releaseYear: 2012,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Isekai", "Fantasy", "Game", "Comedy"]),
    description: "Two genius sibling gamers are transported to a world where all conflicts are decided by games.",
    rating: 8.2,
    popularity: 64000,
    sourceUrl: "https://anilist.co/manga/78399",
    sourceName: "AniList",
    externalId: "ln-78399",
  },
  {
    canonicalTitle: "A Fire Upon the Deep",
    originalTitle: "A Fire Upon the Deep",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1992,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Space Opera", "Epic", "Hard Sci-Fi"]),
    description: "Multiple civilizations at different levels of intelligence race to save the universe from an ancient evil.",
    rating: 8.5,
    popularity: 52000,
    sourceUrl: "https://openlibrary.org/works/OL11000W",
    sourceName: "Open Library",
    externalId: "ol-fire-deep",
  },
  {
    canonicalTitle: "The Demolished Man",
    originalTitle: "The Demolished Man",
    mediaType: MediaType.NOVEL,
    subType: "Sci-Fi",
    releaseYear: 1953,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Mystery", "Thriller", "Telepathy"]),
    description: "A wealthy tycoon attempts to commit murder in a world with telepathic police who can read minds.",
    rating: 8.0,
    popularity: 44000,
    sourceUrl: "https://openlibrary.org/works/OL2010W",
    sourceName: "Open Library",
    externalId: "ol-demolished-man",
  },
  {
    canonicalTitle: "The Hitchhiker's Guide to the Galaxy",
    originalTitle: "The Hitchhiker's Guide to the Galaxy",
    mediaType: MediaType.NOVEL,
    subType: "Comedy",
    releaseYear: 1979,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Comedy", "Sci-Fi", "Satire", "Philosophy"]),
    description: "An Englishman is saved from Earth's destruction and tours the universe with the most remarkable book in the galaxy.",
    rating: 8.8,
    popularity: 82000,
    sourceUrl: "https://openlibrary.org/works/OL13516W",
    sourceName: "Open Library",
    externalId: "ol-hitchhiker",
  },
  {
    canonicalTitle: "Jonathan Strange & Mr Norrell",
    originalTitle: "Jonathan Strange & Mr Norrell",
    mediaType: MediaType.NOVEL,
    subType: "Fantasy",
    releaseYear: 2004,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Historical", "Literary Fiction", "Magic"]),
    description: "Two very different magicians attempt to restore magic to England during the Napoleonic wars.",
    rating: 8.4,
    popularity: 56000,
    sourceUrl: "https://openlibrary.org/works/OL8190330W",
    sourceName: "Open Library",
    externalId: "ol-jonathan-strange",
  },
] as const;
