import { MediaType, MediaStatus } from "@prisma/client";

export const comicTitles = [
  {
    canonicalTitle: "Watchmen",
    originalTitle: "Watchmen",
    mediaType: MediaType.COMIC,
    subType: "Graphic Novel",
    releaseYear: 1986,
    endYear: 1987,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Superhero", "Drama", "Philosophical", "Mystery"]),
    description: "A deconstruction of superhero mythology set in an alternate 1985 where superheroes are outlawed and a nuclear clock ticks down.",
    rating: 9.2,
    popularity: 78000,
    sourceUrl: "https://comicvine.gamespot.com/watchmen/4050-18947/",
    sourceName: "Comic Vine",
    externalId: "cv-18947",
  },
  {
    canonicalTitle: "The Dark Knight Returns",
    originalTitle: "Batman: The Dark Knight Returns",
    mediaType: MediaType.COMIC,
    subType: "Graphic Novel",
    releaseYear: 1986,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Drama", "Dystopia"]),
    description: "A 55-year-old Bruce Wayne comes out of retirement as Batman in a dark, dystopian future Gotham.",
    rating: 9.0,
    popularity: 70000,
    sourceUrl: "https://comicvine.gamespot.com/batman-the-dark-knight-returns/4050-53149/",
    sourceName: "Comic Vine",
    externalId: "cv-53149",
  },
  {
    canonicalTitle: "Maus",
    originalTitle: "Maus: A Survivor's Tale",
    mediaType: MediaType.COMIC,
    subType: "Memoir",
    releaseYear: 1980,
    endYear: 1991,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Historical", "Biography", "Drama", "Holocaust"]),
    description: "A cartoonist interviews his Holocaust-survivor father, depicting Jews as mice and Nazis as cats.",
    rating: 9.2,
    popularity: 72000,
    sourceUrl: "https://openlibrary.org/works/OL16432515W",
    sourceName: "Open Library",
    externalId: "ol-maus",
  },
  {
    canonicalTitle: "Saga",
    originalTitle: "Saga",
    mediaType: MediaType.COMIC,
    subType: "Sci-Fi",
    releaseYear: 2012,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Fantasy", "Drama", "Adult"]),
    description: "A war between two alien civilizations threatens to tear apart a family of refugees from both sides.",
    rating: 8.8,
    popularity: 65000,
    sourceUrl: "https://comicvine.gamespot.com/saga/4050-375132/",
    sourceName: "Comic Vine",
    externalId: "cv-375132",
  },
  {
    canonicalTitle: "The Sandman",
    originalTitle: "The Sandman",
    mediaType: MediaType.COMIC,
    subType: "Fantasy",
    releaseYear: 1989,
    endYear: 1996,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Horror", "Mythology", "Drama"]),
    description: "The Lord of Dreams is imprisoned for decades and must reclaim his realm — a journey through myth, history, and nightmare.",
    rating: 9.2,
    popularity: 75000,
    sourceUrl: "https://comicvine.gamespot.com/the-sandman/4050-15082/",
    sourceName: "Comic Vine",
    externalId: "cv-15082",
  },
  {
    canonicalTitle: "Preacher",
    originalTitle: "Preacher",
    mediaType: MediaType.COMIC,
    subType: "Dark Comedy",
    releaseYear: 1995,
    endYear: 2000,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Horror", "Dark Comedy", "Western", "Supernatural"]),
    description: "A preacher merged with a supernatural entity sets out to find God and make him answer for his abandonment of creation.",
    rating: 8.8,
    popularity: 58000,
    sourceUrl: "https://comicvine.gamespot.com/preacher/4050-6577/",
    sourceName: "Comic Vine",
    externalId: "cv-6577",
  },
  {
    canonicalTitle: "Transmetropolitan",
    originalTitle: "Transmetropolitan",
    mediaType: MediaType.COMIC,
    subType: "Sci-Fi",
    releaseYear: 1997,
    endYear: 2002,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Satire", "Cyberpunk", "Political"]),
    description: "A gonzo journalist returns to the city and uses his pen as a weapon against political corruption.",
    rating: 8.9,
    popularity: 55000,
    sourceUrl: "https://comicvine.gamespot.com/transmetropolitan/4050-13056/",
    sourceName: "Comic Vine",
    externalId: "cv-13056",
  },
  {
    canonicalTitle: "Y: The Last Man",
    originalTitle: "Y: The Last Man",
    mediaType: MediaType.COMIC,
    subType: "Sci-Fi",
    releaseYear: 2002,
    endYear: 2008,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Post-Apocalyptic", "Thriller"]),
    description: "A plague kills every mammal with a Y chromosome — except one young man and his pet monkey.",
    rating: 8.7,
    popularity: 60000,
    sourceUrl: "https://comicvine.gamespot.com/y-the-last-man/4050-17990/",
    sourceName: "Comic Vine",
    externalId: "cv-17990",
  },
  {
    canonicalTitle: "Bone",
    originalTitle: "Bone",
    mediaType: MediaType.COMIC,
    subType: "Fantasy",
    releaseYear: 1991,
    endYear: 2004,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Comedy", "Epic"]),
    description: "Three cartoon cousins get lost in a mysterious fantasy valley and become entangled in an ancient conflict.",
    rating: 8.7,
    popularity: 52000,
    sourceUrl: "https://comicvine.gamespot.com/bone/4050-18947/",
    sourceName: "Comic Vine",
    externalId: "cv-bone",
  },
  {
    canonicalTitle: "Persepolis",
    originalTitle: "Persepolis",
    mediaType: MediaType.COMIC,
    subType: "Memoir",
    releaseYear: 2000,
    endYear: 2003,
    status: MediaStatus.COMPLETED,
    country: "FR",
    language: "fr",
    genres: JSON.stringify(["Biography", "Historical", "Drama", "Political"]),
    description: "An Iranian woman's childhood memories of the Islamic Revolution and her coming of age in Europe.",
    rating: 8.6,
    popularity: 58000,
    sourceUrl: "https://openlibrary.org/works/OL8459686W",
    sourceName: "Open Library",
    externalId: "ol-persepolis",
  },
  {
    canonicalTitle: "Scott Pilgrim vs. the World",
    originalTitle: "Scott Pilgrim's Precious Little Life",
    mediaType: MediaType.COMIC,
    subType: "Indie",
    releaseYear: 2004,
    endYear: 2010,
    status: MediaStatus.COMPLETED,
    country: "CA",
    language: "en",
    genres: JSON.stringify(["Comedy", "Romance", "Action", "Video Game"]),
    description: "A slacker must defeat his new girlfriend's seven evil exes in epic video-game-style battles.",
    rating: 8.4,
    popularity: 64000,
    sourceUrl: "https://comicvine.gamespot.com/scott-pilgrim/4050-53820/",
    sourceName: "Comic Vine",
    externalId: "cv-53820",
  },
  {
    canonicalTitle: "East of West",
    originalTitle: "East of West",
    mediaType: MediaType.COMIC,
    subType: "Sci-Fi",
    releaseYear: 2013,
    endYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Fantasy", "Western", "Apocalyptic"]),
    description: "In an alternate America, the Four Horsemen of the Apocalypse are real, but Death has gone rogue.",
    rating: 8.5,
    popularity: 44000,
    sourceUrl: "https://comicvine.gamespot.com/east-of-west/4050-414895/",
    sourceName: "Comic Vine",
    externalId: "cv-414895",
  },
  {
    canonicalTitle: "Blacksad",
    originalTitle: "Blacksad",
    mediaType: MediaType.COMIC,
    subType: "Noir",
    releaseYear: 2000,
    status: MediaStatus.ONGOING,
    country: "ES",
    language: "es",
    genres: JSON.stringify(["Noir", "Crime", "Mystery", "Drama"]),
    description: "A private detective who is an anthropomorphic black cat solves dark crimes in 1950s America.",
    rating: 8.9,
    popularity: 50000,
    sourceUrl: "https://comicvine.gamespot.com/blacksad/4050-64781/",
    sourceName: "Comic Vine",
    externalId: "cv-64781",
  },
  {
    canonicalTitle: "Asterix",
    originalTitle: "Astérix",
    mediaType: MediaType.COMIC,
    subType: "Historical Comedy",
    releaseYear: 1959,
    status: MediaStatus.ONGOING,
    country: "FR",
    language: "fr",
    genres: JSON.stringify(["Comedy", "Historical", "Adventure", "Satire"]),
    description: "A village of indomitable Gauls uses a magic potion to resist Roman occupation — with comic results.",
    rating: 8.5,
    popularity: 68000,
    sourceUrl: "https://comicvine.gamespot.com/asterix/4050-16083/",
    sourceName: "Comic Vine",
    externalId: "cv-16083",
  },
  {
    canonicalTitle: "The Adventures of Tintin",
    originalTitle: "Les Aventures de Tintin",
    mediaType: MediaType.COMIC,
    subType: "Adventure",
    releaseYear: 1929,
    endYear: 1976,
    status: MediaStatus.COMPLETED,
    country: "BE",
    language: "fr",
    genres: JSON.stringify(["Adventure", "Mystery", "Comedy", "Classic"]),
    description: "A young reporter and his faithful dog Snowy solve mysteries and go on adventures around the world.",
    rating: 8.6,
    popularity: 72000,
    sourceUrl: "https://comicvine.gamespot.com/the-adventures-of-tintin/4050-18032/",
    sourceName: "Comic Vine",
    externalId: "cv-18032",
  },
  {
    canonicalTitle: "V for Vendetta",
    originalTitle: "V for Vendetta",
    mediaType: MediaType.COMIC,
    subType: "Graphic Novel",
    releaseYear: 1982,
    endYear: 1989,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Dystopia", "Political", "Anarchism", "Thriller"]),
    description: "A masked anarchist fights a fascist British government with a young woman caught in the middle.",
    rating: 8.9,
    popularity: 66000,
    sourceUrl: "https://comicvine.gamespot.com/v-for-vendetta/4050-5668/",
    sourceName: "Comic Vine",
    externalId: "cv-5668",
  },
  {
    canonicalTitle: "Kingdom Come",
    originalTitle: "Kingdom Come",
    mediaType: MediaType.COMIC,
    subType: "Graphic Novel",
    releaseYear: 1996,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Drama", "Philosophical", "Epic"]),
    description: "An aging Superman returns from retirement as the next generation of heroes spirals into anarchy.",
    rating: 9.0,
    popularity: 58000,
    sourceUrl: "https://comicvine.gamespot.com/kingdom-come/4050-34044/",
    sourceName: "Comic Vine",
    externalId: "cv-34044",
  },
  {
    canonicalTitle: "All-Star Superman",
    originalTitle: "All-Star Superman",
    mediaType: MediaType.COMIC,
    subType: "Graphic Novel",
    releaseYear: 2005,
    endYear: 2008,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Drama", "Mythology", "Epic"]),
    description: "Superman, told he is dying, sets out to complete twelve labors that define why he is Earth's greatest hero.",
    rating: 9.1,
    popularity: 60000,
    sourceUrl: "https://comicvine.gamespot.com/all-star-superman/4050-147754/",
    sourceName: "Comic Vine",
    externalId: "cv-147754",
  },
  {
    canonicalTitle: "From Hell",
    originalTitle: "From Hell",
    mediaType: MediaType.COMIC,
    subType: "Historical",
    releaseYear: 1989,
    endYear: 1998,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Historical", "Horror", "Mystery", "Philosophical"]),
    description: "An exhaustive, researched theory of Jack the Ripper's identity and the Victorian society that created him.",
    rating: 8.8,
    popularity: 48000,
    sourceUrl: "https://comicvine.gamespot.com/from-hell/4050-27534/",
    sourceName: "Comic Vine",
    externalId: "cv-27534",
  },
  {
    canonicalTitle: "Paper Girls",
    originalTitle: "Paper Girls",
    mediaType: MediaType.COMIC,
    subType: "Sci-Fi",
    releaseYear: 2015,
    endYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Adventure", "Time Travel", "Mystery"]),
    description: "Four paper girls in 1988 Ohio stumble into a time war that sends them across different eras.",
    rating: 8.2,
    popularity: 42000,
    sourceUrl: "https://comicvine.gamespot.com/paper-girls/4050-74494/",
    sourceName: "Comic Vine",
    externalId: "cv-74494",
  },
] as const;
