import { MediaType, MediaStatus } from "@prisma/client";

export const gameTitles = [
  {
    canonicalTitle: "NieR: Automata",
    originalTitle: "NieR:Automata",
    mediaType: MediaType.GAME,
    subType: "Action RPG",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action RPG", "Sci-Fi", "Philosophical", "Post-Apocalyptic"]),
    description: "Android soldiers fight a proxy war for humanity against machines, exploring free will and existence.",
    rating: 9.1,
    popularity: 82000,
    sourceUrl: "https://www.igdb.com/games/nier-automata",
    sourceName: "IGDB",
    externalId: "igdb-nier-automata",
  },
  {
    canonicalTitle: "Disco Elysium",
    originalTitle: "Disco Elysium",
    mediaType: MediaType.GAME,
    subType: "RPG",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "EE",
    language: "en",
    genres: JSON.stringify(["RPG", "Detective", "Philosophical", "Political"]),
    description: "A detective with total amnesia pieces together a murder case and his own identity in a crumbling city.",
    rating: 9.0,
    popularity: 76000,
    sourceUrl: "https://www.igdb.com/games/disco-elysium",
    sourceName: "IGDB",
    externalId: "igdb-disco-elysium",
  },
  {
    canonicalTitle: "Hollow Knight",
    originalTitle: "Hollow Knight",
    mediaType: MediaType.GAME,
    subType: "Metroidvania",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "AU",
    language: "en",
    genres: JSON.stringify(["Metroidvania", "Action", "Platformer", "Dark Fantasy"]),
    description: "A mysterious insect knight explores a vast underground kingdom of insects fallen to a terrible infection.",
    rating: 9.0,
    popularity: 80000,
    sourceUrl: "https://www.igdb.com/games/hollow-knight",
    sourceName: "IGDB",
    externalId: "igdb-hollow-knight",
  },
  {
    canonicalTitle: "Hades",
    originalTitle: "Hades",
    mediaType: MediaType.GAME,
    subType: "Roguelite",
    releaseYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Roguelite", "Action", "Greek Mythology", "Story-Rich"]),
    description: "The son of the god of the dead tries to escape the Underworld while his father sends endless enemies to stop him.",
    rating: 9.3,
    popularity: 86000,
    sourceUrl: "https://www.igdb.com/games/hades",
    sourceName: "IGDB",
    externalId: "igdb-hades",
  },
  {
    canonicalTitle: "Celeste",
    originalTitle: "Celeste",
    mediaType: MediaType.GAME,
    subType: "Platformer",
    releaseYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "CA",
    language: "en",
    genres: JSON.stringify(["Platformer", "Drama", "Mental Health", "Indie"]),
    description: "A young woman climbs a mysterious mountain while confronting her inner demons — a metaphor for anxiety and depression.",
    rating: 9.2,
    popularity: 78000,
    sourceUrl: "https://www.igdb.com/games/celeste",
    sourceName: "IGDB",
    externalId: "igdb-celeste",
  },
  {
    canonicalTitle: "Undertale",
    originalTitle: "Undertale",
    mediaType: MediaType.GAME,
    subType: "RPG",
    releaseYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["RPG", "Comedy", "Pacifist", "Meta"]),
    description: "A child falls underground into a monster-filled world where they can choose to spare or kill every enemy.",
    rating: 9.3,
    popularity: 85000,
    sourceUrl: "https://www.igdb.com/games/undertale",
    sourceName: "IGDB",
    externalId: "igdb-undertale",
  },
  {
    canonicalTitle: "Shadow of the Colossus",
    originalTitle: "ワンダと巨像",
    mediaType: MediaType.GAME,
    subType: "Action Adventure",
    releaseYear: 2005,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action Adventure", "Philosophical", "Boss Rush"]),
    description: "A young man travels to a forbidden land to defeat sixteen colossal creatures to resurrect a girl.",
    rating: 9.4,
    popularity: 72000,
    sourceUrl: "https://www.igdb.com/games/shadow-of-the-colossus",
    sourceName: "IGDB",
    externalId: "igdb-shadow-colossus",
  },
  {
    canonicalTitle: "Bloodborne",
    originalTitle: "Bloodborne",
    mediaType: MediaType.GAME,
    subType: "Action RPG",
    releaseYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "en",
    genres: JSON.stringify(["Action RPG", "Gothic Horror", "Lovecraftian", "Souls-like"]),
    description: "A Hunter investigates the source of a plague transforming citizens of a Gothic city into monsters.",
    rating: 9.1,
    popularity: 80000,
    sourceUrl: "https://www.igdb.com/games/bloodborne",
    sourceName: "IGDB",
    externalId: "igdb-bloodborne",
  },
  {
    canonicalTitle: "Dark Souls",
    originalTitle: "ダークソウル",
    mediaType: MediaType.GAME,
    subType: "Action RPG",
    releaseYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "en",
    genres: JSON.stringify(["Action RPG", "Dark Fantasy", "Souls-like", "Challenging"]),
    description: "An undead warrior journeys through a decaying world to rekindle a fading flame — or let it die.",
    rating: 9.0,
    popularity: 82000,
    sourceUrl: "https://www.igdb.com/games/dark-souls",
    sourceName: "IGDB",
    externalId: "igdb-dark-souls",
  },
  {
    canonicalTitle: "Planescape: Torment",
    originalTitle: "Planescape: Torment",
    mediaType: MediaType.GAME,
    subType: "RPG",
    releaseYear: 1999,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["RPG", "Philosophical", "Fantasy", "Story-Rich"]),
    description: "An immortal amnesiac seeks to discover who he is by exploring a deeply philosophical multiverse.",
    rating: 9.4,
    popularity: 65000,
    sourceUrl: "https://www.igdb.com/games/planescape-torment",
    sourceName: "IGDB",
    externalId: "igdb-planescape",
  },
  {
    canonicalTitle: "Baldur's Gate 3",
    originalTitle: "Baldur's Gate 3",
    mediaType: MediaType.GAME,
    subType: "RPG",
    releaseYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "BE",
    language: "en",
    genres: JSON.stringify(["RPG", "Fantasy", "Turn-Based", "Story-Rich"]),
    description: "After infection by mind flayer parasites, an unlikely group of adventurers must work together to survive.",
    rating: 9.6,
    popularity: 92000,
    sourceUrl: "https://www.igdb.com/games/baldurs-gate-3",
    sourceName: "IGDB",
    externalId: "igdb-bg3",
  },
  {
    canonicalTitle: "The Last of Us",
    originalTitle: "The Last of Us",
    mediaType: MediaType.GAME,
    subType: "Action Adventure",
    releaseYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Action Adventure", "Drama", "Horror", "Post-Apocalyptic"]),
    description: "A smuggler escorts a girl who may be humanity's last hope across a post-pandemic United States.",
    rating: 9.5,
    popularity: 88000,
    sourceUrl: "https://www.igdb.com/games/the-last-of-us",
    sourceName: "IGDB",
    externalId: "igdb-last-of-us",
  },
  {
    canonicalTitle: "Red Dead Redemption 2",
    originalTitle: "Red Dead Redemption 2",
    mediaType: MediaType.GAME,
    subType: "Action Adventure",
    releaseYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Action Adventure", "Western", "Open World", "Drama"]),
    description: "An outlaw on the run with his gang in the dying days of the American frontier era.",
    rating: 9.7,
    popularity: 90000,
    sourceUrl: "https://www.igdb.com/games/red-dead-redemption-2",
    sourceName: "IGDB",
    externalId: "igdb-rdr2",
  },
  {
    canonicalTitle: "Outer Wilds",
    originalTitle: "Outer Wilds",
    mediaType: MediaType.GAME,
    subType: "Exploration",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Exploration", "Mystery", "Sci-Fi", "Philosophical"]),
    description: "An astronaut explores a solar system frozen in a 22-minute time loop before the sun explodes.",
    rating: 9.5,
    popularity: 76000,
    sourceUrl: "https://www.igdb.com/games/outer-wilds",
    sourceName: "IGDB",
    externalId: "igdb-outer-wilds",
  },
  {
    canonicalTitle: "What Remains of Edith Finch",
    originalTitle: "What Remains of Edith Finch",
    mediaType: MediaType.GAME,
    subType: "Walking Simulator",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Walking Simulator", "Drama", "Mystery", "Story-Rich"]),
    description: "A young woman returns to her family's estate to explore the stories of family members who died under mysterious circumstances.",
    rating: 9.0,
    popularity: 70000,
    sourceUrl: "https://www.igdb.com/games/what-remains-of-edith-finch",
    sourceName: "IGDB",
    externalId: "igdb-edith-finch",
  },
  {
    canonicalTitle: "Control",
    originalTitle: "Control",
    mediaType: MediaType.GAME,
    subType: "Action",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "FI",
    language: "en",
    genres: JSON.stringify(["Action", "Sci-Fi", "Mystery", "Metroidvania"]),
    description: "A woman becomes director of a secret government agency that investigates paranormal phenomena.",
    rating: 8.7,
    popularity: 72000,
    sourceUrl: "https://www.igdb.com/games/control-2019",
    sourceName: "IGDB",
    externalId: "igdb-control",
  },
  {
    canonicalTitle: "Cyberpunk 2077",
    originalTitle: "Cyberpunk 2077",
    mediaType: MediaType.GAME,
    subType: "Action RPG",
    releaseYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "PL",
    language: "en",
    genres: JSON.stringify(["Action RPG", "Cyberpunk", "Open World", "Sci-Fi"]),
    description: "A mercenary implanted with a chip containing the consciousness of a legendary rocker fights for survival in Night City.",
    rating: 8.5,
    popularity: 84000,
    sourceUrl: "https://www.igdb.com/games/cyberpunk-2077",
    sourceName: "IGDB",
    externalId: "igdb-cyberpunk",
  },
  {
    canonicalTitle: "Death Stranding",
    originalTitle: "Death Stranding",
    mediaType: MediaType.GAME,
    subType: "Action",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "en",
    genres: JSON.stringify(["Action", "Sci-Fi", "Philosophical", "Drama"]),
    description: "A courier reconnects isolated cities across a shattered America haunted by supernatural entities.",
    rating: 8.2,
    popularity: 70000,
    sourceUrl: "https://www.igdb.com/games/death-stranding",
    sourceName: "IGDB",
    externalId: "igdb-death-stranding",
  },
  {
    canonicalTitle: "Returnal",
    originalTitle: "Returnal",
    mediaType: MediaType.GAME,
    subType: "Roguelite",
    releaseYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "FI",
    language: "en",
    genres: JSON.stringify(["Roguelite", "Sci-Fi", "Shooter", "Psychological"]),
    description: "An astronaut crashes on an alien planet and becomes trapped in a time loop, forced to repeat her fate.",
    rating: 8.8,
    popularity: 68000,
    sourceUrl: "https://www.igdb.com/games/returnal",
    sourceName: "IGDB",
    externalId: "igdb-returnal",
  },
  {
    canonicalTitle: "Pentiment",
    originalTitle: "Pentiment",
    mediaType: MediaType.GAME,
    subType: "Adventure",
    releaseYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Adventure", "Historical", "Mystery", "Drama"]),
    description: "An apprentice illustrator solves murders in a 16th-century Bavarian town, uncovering decades of dark secrets.",
    rating: 9.0,
    popularity: 58000,
    sourceUrl: "https://www.igdb.com/games/pentiment",
    sourceName: "IGDB",
    externalId: "igdb-pentiment",
  },
  {
    canonicalTitle: "Divinity: Original Sin 2",
    originalTitle: "Divinity: Original Sin 2",
    mediaType: MediaType.GAME,
    subType: "RPG",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "BE",
    language: "en",
    genres: JSON.stringify(["RPG", "Fantasy", "Turn-Based", "Strategy"]),
    description: "An outcast Sourcerer fights for freedom — and potentially godhood — in a world that fears magic users.",
    rating: 9.5,
    popularity: 80000,
    sourceUrl: "https://www.igdb.com/games/divinity-original-sin-2",
    sourceName: "IGDB",
    externalId: "igdb-divinity2",
  },
  {
    canonicalTitle: "Katana ZERO",
    originalTitle: "Katana ZERO",
    mediaType: MediaType.GAME,
    subType: "Action",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Action", "Neo-Noir", "Sci-Fi", "Thriller"]),
    description: "A samurai assassin with premonition powers takes on contract kills in a neo-noir setting.",
    rating: 8.9,
    popularity: 65000,
    sourceUrl: "https://www.igdb.com/games/katana-zero",
    sourceName: "IGDB",
    externalId: "igdb-katana-zero",
  },
  {
    canonicalTitle: "Spiritfarer",
    originalTitle: "Spiritfarer",
    mediaType: MediaType.GAME,
    subType: "Simulation",
    releaseYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "CA",
    language: "en",
    genres: JSON.stringify(["Simulation", "Adventure", "Emotional", "Management"]),
    description: "A ferrymaster for the dead sails the spirit world, building a boat and caring for spirits before they pass on.",
    rating: 8.8,
    popularity: 60000,
    sourceUrl: "https://www.igdb.com/games/spiritfarer",
    sourceName: "IGDB",
    externalId: "igdb-spiritfarer",
  },
  {
    canonicalTitle: "Pillars of Eternity",
    originalTitle: "Pillars of Eternity",
    mediaType: MediaType.GAME,
    subType: "RPG",
    releaseYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["RPG", "Fantasy", "Philosophical", "Strategy"]),
    description: "A Watcher with the power to read souls investigates the mystery behind a new kind of illness affecting children.",
    rating: 8.8,
    popularity: 64000,
    sourceUrl: "https://www.igdb.com/games/pillars-of-eternity",
    sourceName: "IGDB",
    externalId: "igdb-poe",
  },
  {
    canonicalTitle: "Horizon Zero Dawn",
    originalTitle: "Horizon Zero Dawn",
    mediaType: MediaType.GAME,
    subType: "Action RPG",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "NL",
    language: "en",
    genres: JSON.stringify(["Action RPG", "Sci-Fi", "Open World", "Post-Apocalyptic"]),
    description: "A hunter in a primitive society uncovers the mysteries of a world ruled by robotic animals.",
    rating: 8.8,
    popularity: 78000,
    sourceUrl: "https://www.igdb.com/games/horizon-zero-dawn",
    sourceName: "IGDB",
    externalId: "igdb-horizon",
  },
] as const;
