import { MediaType, MediaStatus } from "@prisma/client";

export const mangaTitles = [
  {
    canonicalTitle: "Berserk",
    originalTitle: "ベルセルク",
    mediaType: MediaType.MANGA,
    subType: "Dark Fantasy",
    releaseYear: 1989,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Dark Fantasy", "Action", "Drama", "Horror"]),
    description: "A lone swordsman battles demonic forces while searching for his former mercenary leader who betrayed him.",
    rating: 9.4,
    popularity: 80000,
    sourceUrl: "https://anilist.co/manga/30002",
    sourceName: "AniList",
    externalId: "m-30002",
  },
  {
    canonicalTitle: "Vagabond",
    originalTitle: "バガボンド",
    mediaType: MediaType.MANGA,
    subType: "Historical",
    releaseYear: 1998,
    status: MediaStatus.HIATUS,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Historical", "Action", "Drama", "Samurai"]),
    description: "A fictionalized account of Miyamoto Musashi's journey to become the greatest swordsman in Japan.",
    rating: 9.4,
    popularity: 70000,
    sourceUrl: "https://anilist.co/manga/30654",
    sourceName: "AniList",
    externalId: "m-30654",
  },
  {
    canonicalTitle: "One Punch Man",
    originalTitle: "ワンパンマン",
    mediaType: MediaType.MANGA,
    subType: "Superhero",
    releaseYear: 2012,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Superhero", "Action", "Comedy", "Parody"]),
    description: "A hero so powerful he defeats any enemy with a single punch suffers from the existential boredom of being unbeatable.",
    rating: 8.9,
    popularity: 82000,
    sourceUrl: "https://anilist.co/manga/75989",
    sourceName: "AniList",
    externalId: "m-75989",
  },
  {
    canonicalTitle: "Chainsaw Man",
    originalTitle: "チェンソーマン",
    mediaType: MediaType.MANGA,
    subType: "Dark Fantasy",
    releaseYear: 2018,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Dark Fantasy", "Horror", "Comedy"]),
    description: "A young devil hunter merges with his chainsaw devil dog and joins a government devil-hunting agency.",
    rating: 8.8,
    popularity: 84000,
    sourceUrl: "https://anilist.co/manga/107233",
    sourceName: "AniList",
    externalId: "m-107233",
  },
  {
    canonicalTitle: "JoJo's Bizarre Adventure",
    originalTitle: "ジョジョの奇妙な冒険",
    mediaType: MediaType.MANGA,
    subType: "Adventure",
    releaseYear: 1987,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Supernatural", "Comedy"]),
    description: "Multiple generations of the Joestar family encounter supernatural enemies, each with unique powers.",
    rating: 8.7,
    popularity: 79000,
    sourceUrl: "https://anilist.co/manga/1534",
    sourceName: "AniList",
    externalId: "m-1534",
  },
  {
    canonicalTitle: "Goodnight Punpun",
    originalTitle: "おやすみプンプン",
    mediaType: MediaType.MANGA,
    subType: "Drama",
    releaseYear: 2007,
    endYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Psychological", "Romance", "Slice of Life"]),
    description: "A boy depicted as a simple bird shape grows up through trauma, love, depression, and violence.",
    rating: 8.9,
    popularity: 65000,
    sourceUrl: "https://anilist.co/manga/36null",
    sourceName: "AniList",
    externalId: "m-punpun",
  },
  {
    canonicalTitle: "Spy x Family",
    originalTitle: "SPY×FAMILY",
    mediaType: MediaType.MANGA,
    subType: "Comedy",
    releaseYear: 2019,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Comedy", "Action", "Spy", "Family"]),
    description: "A spy, assassin, and telepath form a fake family, unaware of each other's secrets.",
    rating: 8.5,
    popularity: 78000,
    sourceUrl: "https://anilist.co/manga/108556",
    sourceName: "AniList",
    externalId: "m-108556",
  },
  {
    canonicalTitle: "Blue Period",
    originalTitle: "ブルーピリオド",
    mediaType: MediaType.MANGA,
    subType: "Art",
    releaseYear: 2017,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Slice of Life", "Art", "School"]),
    description: "A popular but hollow student discovers painting and pursues entry to Japan's most prestigious art school.",
    rating: 8.7,
    popularity: 56000,
    sourceUrl: "https://anilist.co/manga/103877",
    sourceName: "AniList",
    externalId: "m-103877",
  },
  {
    canonicalTitle: "Dungeon Meshi",
    originalTitle: "ダンジョン飯",
    mediaType: MediaType.MANGA,
    subType: "Fantasy",
    releaseYear: 2014,
    endYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Comedy", "Cooking"]),
    description: "An adventurer's party cooks and eats dungeon monsters to survive as they descend to rescue a devoured teammate.",
    rating: 9.0,
    popularity: 74000,
    sourceUrl: "https://anilist.co/manga/85191",
    sourceName: "AniList",
    externalId: "m-85191",
  },
  {
    canonicalTitle: "20th Century Boys",
    originalTitle: "20世紀少年",
    mediaType: MediaType.MANGA,
    subType: "Thriller",
    releaseYear: 1999,
    endYear: 2006,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Thriller", "Mystery", "Sci-Fi", "Drama"]),
    description: "A convenience store owner discovers a dangerous cult may be acting out a 'Book of Prophecy' his childhood friend created.",
    rating: 8.9,
    popularity: 60000,
    sourceUrl: "https://anilist.co/manga/30014",
    sourceName: "AniList",
    externalId: "m-30014",
  },
  {
    canonicalTitle: "Pluto",
    originalTitle: "PLUTO",
    mediaType: MediaType.MANGA,
    subType: "Sci-Fi",
    releaseYear: 2003,
    endYear: 2009,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Drama", "Mystery"]),
    description: "A reimagining of Astro Boy's 'The Greatest Robot on Earth' arc, exploring robot rights and the roots of hatred.",
    rating: 8.9,
    popularity: 55000,
    sourceUrl: "https://anilist.co/manga/30041",
    sourceName: "AniList",
    externalId: "m-30041",
  },
  {
    canonicalTitle: "Dorohedoro",
    originalTitle: "ドロヘドロ",
    mediaType: MediaType.MANGA,
    subType: "Dark Fantasy",
    releaseYear: 2000,
    endYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Dark Fantasy", "Action", "Comedy", "Mystery"]),
    description: "A man with a reptile head and no memories seeks the sorcerer who transformed him in a gritty industrial wasteland.",
    rating: 8.9,
    popularity: 59000,
    sourceUrl: "https://anilist.co/manga/30030",
    sourceName: "AniList",
    externalId: "m-30030",
  },
  {
    canonicalTitle: "Frieren: Beyond Journey's End",
    originalTitle: "葬送のフリーレン",
    mediaType: MediaType.MANGA,
    subType: "Fantasy",
    releaseYear: 2020,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Drama", "Slice of Life"]),
    description: "The manga source of the acclaimed anime series about an elven mage reckoning with time and mortality.",
    rating: 8.9,
    popularity: 72000,
    sourceUrl: "https://anilist.co/manga/118586",
    sourceName: "AniList",
    externalId: "m-118586",
  },
  {
    canonicalTitle: "Witch Hat Atelier",
    originalTitle: "とんがり帽子のアトリエ",
    mediaType: MediaType.MANGA,
    subType: "Fantasy",
    releaseYear: 2016,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Magic", "Drama"]),
    description: "A girl discovers magic is writing, not talent, and enters a secret world of witches and forbidden knowledge.",
    rating: 8.8,
    popularity: 54000,
    sourceUrl: "https://anilist.co/manga/96886",
    sourceName: "AniList",
    externalId: "m-96886",
  },
  {
    canonicalTitle: "Golden Kamuy",
    originalTitle: "ゴールデンカムイ",
    mediaType: MediaType.MANGA,
    subType: "Historical",
    releaseYear: 2014,
    endYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Historical", "Action", "Adventure", "Mystery"]),
    description: "A veteran soldier and a young Ainu girl hunt for hidden gold across 1900s Hokkaido, facing deadly rivals.",
    rating: 8.9,
    popularity: 63000,
    sourceUrl: "https://anilist.co/manga/78314",
    sourceName: "AniList",
    externalId: "m-78314",
  },
  {
    canonicalTitle: "Blue Lock",
    originalTitle: "ブルーロック",
    mediaType: MediaType.MANGA,
    subType: "Sports",
    releaseYear: 2018,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sports", "Action", "Drama", "School"]),
    description: "Three hundred high school strikers compete in a brutal training facility to become Japan's ultimate football ego.",
    rating: 8.4,
    popularity: 70000,
    sourceUrl: "https://anilist.co/manga/116661",
    sourceName: "AniList",
    externalId: "m-116661",
  },
  {
    canonicalTitle: "Lone Wolf and Cub",
    originalTitle: "子連れ狼",
    mediaType: MediaType.MANGA,
    subType: "Samurai",
    releaseYear: 1970,
    endYear: 1976,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Historical", "Action", "Drama", "Samurai"]),
    description: "A former shogunate executioner and his infant son walk the 'Demon Way in Hell' seeking revenge.",
    rating: 9.0,
    popularity: 48000,
    sourceUrl: "https://anilist.co/manga/30006",
    sourceName: "AniList",
    externalId: "m-30006",
  },
  {
    canonicalTitle: "Yotsuba&!",
    originalTitle: "よつばと！",
    mediaType: MediaType.MANGA,
    subType: "Slice of Life",
    releaseYear: 2003,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Slice of Life", "Comedy", "Family"]),
    description: "A five-year-old girl with green pigtails discovers the everyday wonders of life with joyful curiosity.",
    rating: 9.1,
    popularity: 57000,
    sourceUrl: "https://anilist.co/manga/30031",
    sourceName: "AniList",
    externalId: "m-30031",
  },
  {
    canonicalTitle: "Solanin",
    originalTitle: "ソラニン",
    mediaType: MediaType.MANGA,
    subType: "Drama",
    releaseYear: 2005,
    endYear: 2006,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Slice of Life", "Music", "Romance"]),
    description: "Two young adults in Tokyo wrestle with the uncertainty of their futures and the dreams they fear to pursue.",
    rating: 8.3,
    popularity: 42000,
    sourceUrl: "https://anilist.co/manga/30095",
    sourceName: "AniList",
    externalId: "m-30095",
  },
  {
    canonicalTitle: "My Hero Academia",
    originalTitle: "僕のヒーローアカデミア",
    mediaType: MediaType.MANGA,
    subType: "Shonen",
    releaseYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Superhero", "School", "Adventure"]),
    description: "The manga source for the hit anime series about a powerless boy in a world of superpowers.",
    rating: 8.0,
    popularity: 80000,
    sourceUrl: "https://anilist.co/manga/75989",
    sourceName: "AniList",
    externalId: "m-75983",
  },
  {
    canonicalTitle: "Attack on Titan",
    originalTitle: "進撃の巨人",
    mediaType: MediaType.MANGA,
    subType: "Dark Fantasy",
    releaseYear: 2009,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Dark Fantasy", "Mystery", "Drama"]),
    description: "The manga that spawned the globally acclaimed anime series about humanity's last stand against giants.",
    rating: 8.9,
    popularity: 85000,
    sourceUrl: "https://anilist.co/manga/53390",
    sourceName: "AniList",
    externalId: "m-53390",
  },
  {
    canonicalTitle: "Nausicaä of the Valley of the Wind",
    originalTitle: "風の谷のナウシカ",
    mediaType: MediaType.MANGA,
    subType: "Sci-Fi",
    releaseYear: 1982,
    endYear: 1994,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Fantasy", "Adventure", "Ecological"]),
    description: "Miyazaki's epic manga — deeper and darker than the film — about a princess navigating a post-apocalyptic world.",
    rating: 9.0,
    popularity: 52000,
    sourceUrl: "https://anilist.co/manga/30009",
    sourceName: "AniList",
    externalId: "m-30009",
  },
  {
    canonicalTitle: "Kingdom",
    originalTitle: "キングダム",
    mediaType: MediaType.MANGA,
    subType: "Historical",
    releaseYear: 2006,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Historical", "Action", "War", "Drama"]),
    description: "An orphan slave boy fights to become the greatest general under heaven during the unification of China.",
    rating: 8.7,
    popularity: 65000,
    sourceUrl: "https://anilist.co/manga/30670",
    sourceName: "AniList",
    externalId: "m-30670",
  },
  {
    canonicalTitle: "Tokyo Ghoul",
    originalTitle: "東京喰種トーキョーグール",
    mediaType: MediaType.MANGA,
    subType: "Dark Fantasy",
    releaseYear: 2011,
    endYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Dark Fantasy", "Horror", "Action", "Psychological"]),
    description: "A college student becomes half-ghoul after a deadly encounter, forced to live between two worlds.",
    rating: 8.1,
    popularity: 72000,
    sourceUrl: "https://anilist.co/manga/46324",
    sourceName: "AniList",
    externalId: "m-46324",
  },
  {
    canonicalTitle: "Homunculus",
    originalTitle: "ホムンクルス",
    mediaType: MediaType.MANGA,
    subType: "Psychological",
    releaseYear: 2003,
    endYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Psychological", "Mystery", "Drama", "Supernatural"]),
    description: "A homeless man undergoes trepanation surgery and develops the ability to see others' psychological traumas.",
    rating: 8.5,
    popularity: 44000,
    sourceUrl: "https://anilist.co/manga/30019",
    sourceName: "AniList",
    externalId: "m-30019",
  },
  {
    canonicalTitle: "Eden: It's an Endless World!",
    originalTitle: "エデン〜It's an Endless World！〜",
    mediaType: MediaType.MANGA,
    subType: "Sci-Fi",
    releaseYear: 1997,
    endYear: 2008,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Action", "Drama", "Cyberpunk"]),
    description: "In a post-pandemic world controlled by a shadowy organization, a young man searches for his missing father.",
    rating: 8.5,
    popularity: 38000,
    sourceUrl: "https://anilist.co/manga/30016",
    sourceName: "AniList",
    externalId: "m-30016",
  },
  {
    canonicalTitle: "Fullmetal Alchemist",
    originalTitle: "鋼の錬金術師",
    mediaType: MediaType.MANGA,
    subType: "Adventure",
    releaseYear: 2001,
    endYear: 2010,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Adventure", "Fantasy", "Drama"]),
    description: "The manga source for Brotherhood — two brothers seek the Philosopher's Stone to restore their bodies.",
    rating: 9.0,
    popularity: 82000,
    sourceUrl: "https://anilist.co/manga/25",
    sourceName: "AniList",
    externalId: "m-25",
  },
  {
    canonicalTitle: "Akira",
    originalTitle: "AKIRA",
    mediaType: MediaType.MANGA,
    subType: "Cyberpunk",
    releaseYear: 1982,
    endYear: 1990,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Cyberpunk", "Sci-Fi", "Action", "Psychological"]),
    description: "The original manga is far more expansive than the film — a post-war Tokyo crumbles under psychic power and politics.",
    rating: 8.8,
    popularity: 64000,
    sourceUrl: "https://anilist.co/manga/47",
    sourceName: "AniList",
    externalId: "m-47",
  },
  {
    canonicalTitle: "Vinland Saga",
    originalTitle: "ヴィンランド・サガ",
    mediaType: MediaType.MANGA,
    subType: "Historical",
    releaseYear: 2005,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Historical", "Action", "Adventure", "Drama"]),
    description: "The manga source of the acclaimed anime — a Viking boy's journey from violence toward something greater.",
    rating: 9.1,
    popularity: 70000,
    sourceUrl: "https://anilist.co/manga/30012",
    sourceName: "AniList",
    externalId: "m-30012",
  },
  {
    canonicalTitle: "Skip and Loafer",
    originalTitle: "スキップとローファー",
    mediaType: MediaType.MANGA,
    subType: "Romance",
    releaseYear: 2018,
    status: MediaStatus.ONGOING,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Romance", "Slice of Life", "School", "Comedy"]),
    description: "A girl from rural Japan arrives in Tokyo with enormous ambition and natural warmth that changes everyone around her.",
    rating: 8.6,
    popularity: 47000,
    sourceUrl: "https://anilist.co/manga/112221",
    sourceName: "AniList",
    externalId: "m-112221",
  },
  {
    canonicalTitle: "Blame!",
    originalTitle: "BLAME!",
    mediaType: MediaType.MANGA,
    subType: "Cyberpunk",
    releaseYear: 1997,
    endYear: 2003,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sci-Fi", "Cyberpunk", "Action", "Post-Apocalyptic"]),
    description: "A lone gunman traverses an infinitely expanding megastructure in a far future humanity is nearly extinct.",
    rating: 8.5,
    popularity: 45000,
    sourceUrl: "https://anilist.co/manga/30021",
    sourceName: "AniList",
    externalId: "m-30021",
  },
] as const;
