import { MediaType, MediaStatus } from "@prisma/client";

export const movieTitles = [
  // Studio Ghibli
  {
    canonicalTitle: "Spirited Away",
    originalTitle: "千と千尋の神隠し",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2001,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Anime"]),
    description: "A girl trapped in a spirit world works in a bathhouse for supernatural beings to rescue her parents.",
    rating: 8.9,
    popularity: 92000,
    duration: 125,
    sourceUrl: "https://www.themoviedb.org/movie/129",
    sourceName: "TMDB",
    externalId: "tmdb-129",
  },
  {
    canonicalTitle: "Princess Mononoke",
    originalTitle: "もののけ姫",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1997,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Anime", "Historical"]),
    description: "A young prince mediates between forest gods and an industrializing human settlement that threatens nature.",
    rating: 8.7,
    popularity: 82000,
    duration: 134,
    sourceUrl: "https://www.themoviedb.org/movie/128",
    sourceName: "TMDB",
    externalId: "tmdb-128",
  },
  {
    canonicalTitle: "My Neighbor Totoro",
    originalTitle: "となりのトトロ",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1988,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Family", "Anime"]),
    description: "Two sisters encounter benevolent forest spirits while their mother recovers from illness in rural Japan.",
    rating: 8.2,
    popularity: 75000,
    duration: 86,
    sourceUrl: "https://www.themoviedb.org/movie/8392",
    sourceName: "TMDB",
    externalId: "tmdb-8392",
  },
  {
    canonicalTitle: "Howl's Moving Castle",
    originalTitle: "ハウルの動く城",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2004,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Romance", "Adventure", "Anime"]),
    description: "A young hat maker is cursed to be old and seeks the wizard Howl in his magical walking castle.",
    rating: 8.2,
    popularity: 78000,
    duration: 119,
    sourceUrl: "https://www.themoviedb.org/movie/4935",
    sourceName: "TMDB",
    externalId: "tmdb-4935",
  },
  {
    canonicalTitle: "Grave of the Fireflies",
    originalTitle: "火垂るの墓",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1988,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "War", "Historical", "Anime"]),
    description: "Two siblings struggle to survive in Japan during the final months of World War II.",
    rating: 8.5,
    popularity: 70000,
    duration: 89,
    sourceUrl: "https://www.themoviedb.org/movie/12477",
    sourceName: "TMDB",
    externalId: "tmdb-12477",
  },
  {
    canonicalTitle: "Castle in the Sky",
    originalTitle: "天空の城ラピュタ",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1986,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Adventure", "Sci-Fi", "Anime"]),
    description: "A boy and a girl with a magical crystal search for the legendary floating island of Laputa.",
    rating: 8.1,
    popularity: 66000,
    duration: 124,
    sourceUrl: "https://www.themoviedb.org/movie/10515",
    sourceName: "TMDB",
    externalId: "tmdb-10515",
  },
  {
    canonicalTitle: "The Wind Rises",
    originalTitle: "風立ちぬ",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Historical", "Drama", "Romance", "Anime"]),
    description: "A fictionalized account of Jiro Horikoshi, the designer of the Mitsubishi A6M Zero fighter.",
    rating: 7.8,
    popularity: 58000,
    duration: 126,
    sourceUrl: "https://www.themoviedb.org/movie/149870",
    sourceName: "TMDB",
    externalId: "tmdb-149870",
  },
  // Western Animation Films
  {
    canonicalTitle: "Spider-Man: Into the Spider-Verse",
    originalTitle: "Spider-Man: Into the Spider-Verse",
    mediaType: MediaType.MOVIE,
    subType: "Animated Film",
    releaseYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Superhero", "Animation", "Action", "Adventure"]),
    description: "Miles Morales becomes Spider-Man and teams up with alternate universe versions of the hero.",
    rating: 8.4,
    popularity: 88000,
    duration: 117,
    sourceUrl: "https://www.themoviedb.org/movie/324857",
    sourceName: "TMDB",
    externalId: "tmdb-324857",
  },
  {
    canonicalTitle: "The Iron Giant",
    originalTitle: "The Iron Giant",
    mediaType: MediaType.MOVIE,
    subType: "Animated Film",
    releaseYear: 1999,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Animation", "Sci-Fi", "Drama", "Family"]),
    description: "A young boy befriends a giant alien robot during the Cold War era.",
    rating: 8.1,
    popularity: 65000,
    duration: 86,
    sourceUrl: "https://www.themoviedb.org/movie/10386",
    sourceName: "TMDB",
    externalId: "tmdb-10386",
  },
  {
    canonicalTitle: "Wolfwalkers",
    originalTitle: "Wolfwalkers",
    mediaType: MediaType.MOVIE,
    subType: "Animated Film",
    releaseYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "IE",
    language: "en",
    genres: JSON.stringify(["Animation", "Fantasy", "Adventure", "Family"]),
    description: "A hunter's daughter befriends a wild girl who can transform into a wolf when she sleeps.",
    rating: 8.1,
    popularity: 52000,
    duration: 103,
    sourceUrl: "https://www.themoviedb.org/movie/441130",
    sourceName: "TMDB",
    externalId: "tmdb-441130",
  },
  {
    canonicalTitle: "Kubo and the Two Strings",
    originalTitle: "Kubo and the Two Strings",
    mediaType: MediaType.MOVIE,
    subType: "Animated Film",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Animation", "Fantasy", "Adventure", "Family"]),
    description: "A young boy must find a magical suit of armor to defeat an evil spirit in a quest inspired by Japanese mythology.",
    rating: 7.8,
    popularity: 60000,
    duration: 101,
    sourceUrl: "https://www.themoviedb.org/movie/313297",
    sourceName: "TMDB",
    externalId: "tmdb-313297",
  },
  // International Live-Action Films
  {
    canonicalTitle: "Parasite",
    originalTitle: "기생충",
    mediaType: MediaType.MOVIE,
    subType: "Thriller",
    releaseYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "KR",
    language: "ko",
    genres: JSON.stringify(["Thriller", "Drama", "Dark Comedy", "Social Commentary"]),
    description: "A poor family schemes to infiltrate a wealthy household, with unforeseen and violent consequences.",
    rating: 8.6,
    popularity: 85000,
    duration: 132,
    sourceUrl: "https://www.themoviedb.org/movie/496243",
    sourceName: "TMDB",
    externalId: "tmdb-496243",
  },
  {
    canonicalTitle: "Train to Busan",
    originalTitle: "부산행",
    mediaType: MediaType.MOVIE,
    subType: "Horror",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "KR",
    language: "ko",
    genres: JSON.stringify(["Horror", "Action", "Thriller", "Drama"]),
    description: "A father and daughter fight for survival on a train during a zombie apocalypse outbreak.",
    rating: 7.7,
    popularity: 72000,
    duration: 118,
    sourceUrl: "https://www.themoviedb.org/movie/396535",
    sourceName: "TMDB",
    externalId: "tmdb-396535",
  },
  {
    canonicalTitle: "Oldboy",
    originalTitle: "올드보이",
    mediaType: MediaType.MOVIE,
    subType: "Thriller",
    releaseYear: 2003,
    status: MediaStatus.COMPLETED,
    country: "KR",
    language: "ko",
    genres: JSON.stringify(["Thriller", "Mystery", "Action", "Drama"]),
    description: "A man imprisoned for 15 years without explanation is released and given 5 days to find his captor.",
    rating: 8.4,
    popularity: 78000,
    duration: 120,
    sourceUrl: "https://www.themoviedb.org/movie/670",
    sourceName: "TMDB",
    externalId: "tmdb-670",
  },
  {
    canonicalTitle: "Seven Samurai",
    originalTitle: "七人の侍",
    mediaType: MediaType.MOVIE,
    subType: "Samurai",
    releaseYear: 1954,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Action", "Drama", "Historical", "Samurai"]),
    description: "A poor village hires seven masterless samurai to defend itself against bandits.",
    rating: 8.6,
    popularity: 68000,
    duration: 207,
    sourceUrl: "https://www.themoviedb.org/movie/346",
    sourceName: "TMDB",
    externalId: "tmdb-346",
  },
  {
    canonicalTitle: "Rashomon",
    originalTitle: "羅生門",
    mediaType: MediaType.MOVIE,
    subType: "Drama",
    releaseYear: 1950,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Drama", "Mystery", "Historical", "Crime"]),
    description: "A murder is told from four contradictory perspectives, exploring the subjectivity of truth.",
    rating: 8.2,
    popularity: 55000,
    duration: 88,
    sourceUrl: "https://www.themoviedb.org/movie/548",
    sourceName: "TMDB",
    externalId: "tmdb-548",
  },
  {
    canonicalTitle: "Battle Royale",
    originalTitle: "バトル・ロワイアル",
    mediaType: MediaType.MOVIE,
    subType: "Thriller",
    releaseYear: 2000,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Thriller", "Action", "Dystopia", "Horror"]),
    description: "A class of ninth graders is forced by the government to fight each other to the death on an island.",
    rating: 7.6,
    popularity: 65000,
    duration: 113,
    sourceUrl: "https://www.themoviedb.org/movie/9918",
    sourceName: "TMDB",
    externalId: "tmdb-9918",
  },
  {
    canonicalTitle: "The Raid",
    originalTitle: "Serbuan maut",
    mediaType: MediaType.MOVIE,
    subType: "Action",
    releaseYear: 2011,
    status: MediaStatus.COMPLETED,
    country: "ID",
    language: "id",
    genres: JSON.stringify(["Action", "Thriller", "Crime"]),
    description: "A SWAT team raids an apartment block run by a drug lord and must fight their way through every floor.",
    rating: 7.6,
    popularity: 63000,
    duration: 101,
    sourceUrl: "https://www.themoviedb.org/movie/82654",
    sourceName: "TMDB",
    externalId: "tmdb-82654",
  },
  {
    canonicalTitle: "Snowpiercer",
    originalTitle: "Snowpiercer",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "KR",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Action", "Drama", "Thriller"]),
    description: "Survivors of a frozen Earth live on a perpetually moving train divided by class system.",
    rating: 7.1,
    popularity: 70000,
    duration: 126,
    sourceUrl: "https://www.themoviedb.org/movie/109445",
    sourceName: "TMDB",
    externalId: "tmdb-109445",
  },
  {
    canonicalTitle: "City of God",
    originalTitle: "Cidade de Deus",
    mediaType: MediaType.MOVIE,
    subType: "Crime",
    releaseYear: 2002,
    status: MediaStatus.COMPLETED,
    country: "BR",
    language: "pt",
    genres: JSON.stringify(["Crime", "Drama", "Thriller"]),
    description: "The rise of crime in a Rio de Janeiro slum over three decades, narrated by a boy who wants to be a photographer.",
    rating: 8.6,
    popularity: 80000,
    duration: 130,
    sourceUrl: "https://www.themoviedb.org/movie/598",
    sourceName: "TMDB",
    externalId: "tmdb-598",
  },
  // Hollywood Sci-Fi / Fantasy
  {
    canonicalTitle: "2001: A Space Odyssey",
    originalTitle: "2001: A Space Odyssey",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 1968,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Mystery", "Philosophical"]),
    description: "A space voyage to Jupiter descends into terror when the ship's AI becomes adversarial.",
    rating: 8.3,
    popularity: 75000,
    duration: 149,
    sourceUrl: "https://www.themoviedb.org/movie/62",
    sourceName: "TMDB",
    externalId: "tmdb-62",
  },
  {
    canonicalTitle: "Blade Runner 2049",
    originalTitle: "Blade Runner 2049",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Mystery", "Cyberpunk"]),
    description: "A new blade runner discovers a long-buried secret that could plunge society into chaos.",
    rating: 8.0,
    popularity: 78000,
    duration: 164,
    sourceUrl: "https://www.themoviedb.org/movie/335984",
    sourceName: "TMDB",
    externalId: "tmdb-335984",
  },
  {
    canonicalTitle: "Everything Everywhere All at Once",
    originalTitle: "Everything Everywhere All at Once",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Comedy", "Drama", "Fantasy", "Multiverse"]),
    description: "A laundromat owner discovers she can access parallel lives to stop a powerful evil that threatens the multiverse.",
    rating: 7.9,
    popularity: 82000,
    duration: 139,
    sourceUrl: "https://www.themoviedb.org/movie/545611",
    sourceName: "TMDB",
    externalId: "tmdb-545611",
  },
  {
    canonicalTitle: "Annihilation",
    originalTitle: "Annihilation",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Horror", "Mystery", "Thriller"]),
    description: "A biologist goes on a secret expedition into a quarantined zone where nature mutates in terrifying ways.",
    rating: 7.5,
    popularity: 70000,
    duration: 115,
    sourceUrl: "https://www.themoviedb.org/movie/300668",
    sourceName: "TMDB",
    externalId: "tmdb-300668",
  },
  {
    canonicalTitle: "Arrival",
    originalTitle: "Arrival",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2016,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Mystery", "Language"]),
    description: "A linguist works with the military to communicate with extraterrestrial visitors before global war breaks out.",
    rating: 7.9,
    popularity: 79000,
    duration: 116,
    sourceUrl: "https://www.themoviedb.org/movie/329865",
    sourceName: "TMDB",
    externalId: "tmdb-329865",
  },
  {
    canonicalTitle: "Mad Max: Fury Road",
    originalTitle: "Mad Max: Fury Road",
    mediaType: MediaType.MOVIE,
    subType: "Action",
    releaseYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "AU",
    language: "en",
    genres: JSON.stringify(["Action", "Sci-Fi", "Adventure", "Post-Apocalyptic"]),
    description: "In a post-apocalyptic wasteland, a rebel woman and an enslaved man flee a warlord across a barren desert.",
    rating: 8.1,
    popularity: 84000,
    duration: 120,
    sourceUrl: "https://www.themoviedb.org/movie/76341",
    sourceName: "TMDB",
    externalId: "tmdb-76341",
  },
  {
    canonicalTitle: "Interstellar",
    originalTitle: "Interstellar",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Adventure"]),
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    rating: 8.7,
    popularity: 90000,
    duration: 169,
    sourceUrl: "https://www.themoviedb.org/movie/157336",
    sourceName: "TMDB",
    externalId: "tmdb-157336",
  },
  {
    canonicalTitle: "The Matrix",
    originalTitle: "The Matrix",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 1999,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Action", "Cyberpunk", "Philosophical"]),
    description: "A computer hacker discovers the world he lives in is a simulated reality and joins a rebellion.",
    rating: 8.7,
    popularity: 91000,
    duration: 136,
    sourceUrl: "https://www.themoviedb.org/movie/603",
    sourceName: "TMDB",
    externalId: "tmdb-603",
  },
  {
    canonicalTitle: "Dune",
    originalTitle: "Dune",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Adventure", "Drama", "Epic"]),
    description: "A noble's son is sent to a desert planet, home to the universe's most precious substance.",
    rating: 8.0,
    popularity: 82000,
    duration: 155,
    sourceUrl: "https://www.themoviedb.org/movie/438631",
    sourceName: "TMDB",
    externalId: "tmdb-438631",
  },
  {
    canonicalTitle: "The Breadwinner",
    originalTitle: "The Breadwinner",
    mediaType: MediaType.MOVIE,
    subType: "Animated Film",
    releaseYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "IE",
    language: "en",
    genres: JSON.stringify(["Animation", "Drama", "War", "Family"]),
    description: "An Afghan girl disguises herself as a boy to support her family under Taliban rule.",
    rating: 7.7,
    popularity: 42000,
    duration: 94,
    sourceUrl: "https://www.themoviedb.org/movie/422302",
    sourceName: "TMDB",
    externalId: "tmdb-422302",
  },
  {
    canonicalTitle: "Pan's Labyrinth",
    originalTitle: "El laberinto del fauno",
    mediaType: MediaType.MOVIE,
    subType: "Fantasy",
    releaseYear: 2006,
    status: MediaStatus.COMPLETED,
    country: "ES",
    language: "es",
    genres: JSON.stringify(["Fantasy", "Drama", "Historical", "Dark Fantasy"]),
    description: "A young girl escapes post-war Spain's brutal reality by entering a dark fairy tale world.",
    rating: 8.2,
    popularity: 76000,
    duration: 118,
    sourceUrl: "https://www.themoviedb.org/movie/1417",
    sourceName: "TMDB",
    externalId: "tmdb-1417",
  },
  {
    canonicalTitle: "Inception",
    originalTitle: "Inception",
    mediaType: MediaType.MOVIE,
    subType: "Sci-Fi",
    releaseYear: 2010,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Action", "Mystery"]),
    description: "A thief who steals ideas from dreams is given a chance to plant an idea as inception.",
    rating: 8.8,
    popularity: 93000,
    duration: 148,
    sourceUrl: "https://www.themoviedb.org/movie/27205",
    sourceName: "TMDB",
    externalId: "tmdb-27205",
  },
  {
    canonicalTitle: "Suspiria",
    originalTitle: "Suspiria",
    mediaType: MediaType.MOVIE,
    subType: "Horror",
    releaseYear: 1977,
    status: MediaStatus.COMPLETED,
    country: "IT",
    language: "it",
    genres: JSON.stringify(["Horror", "Giallo", "Supernatural", "Mystery"]),
    description: "An American dancer joins a prestigious dance academy in Germany that harbors a coven of witches.",
    rating: 7.5,
    popularity: 55000,
    duration: 99,
    sourceUrl: "https://www.themoviedb.org/movie/3244",
    sourceName: "TMDB",
    externalId: "tmdb-3244",
  },
  {
    canonicalTitle: "The First Slam Dunk",
    originalTitle: "THE FIRST SLAM DUNK",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Sports", "Drama", "Anime"]),
    description: "A retelling of a crucial basketball match from the classic manga, focusing on point guard Ryota Miyagi.",
    rating: 8.7,
    popularity: 64000,
    duration: 124,
    sourceUrl: "https://anilist.co/anime/120377",
    sourceName: "AniList",
    externalId: "tmdb-120377",
  },
  {
    canonicalTitle: "Nausicaä of the Valley of the Wind",
    originalTitle: "風の谷のナウシカ",
    mediaType: MediaType.MOVIE,
    subType: "Anime Film",
    releaseYear: 1984,
    status: MediaStatus.COMPLETED,
    country: "JP",
    language: "ja",
    genres: JSON.stringify(["Fantasy", "Sci-Fi", "Adventure", "Ecological"]),
    description: "A princess of a small post-apocalyptic kingdom navigates a decaying world while trying to prevent war.",
    rating: 8.1,
    popularity: 60000,
    duration: 117,
    sourceUrl: "https://www.themoviedb.org/movie/39176",
    sourceName: "TMDB",
    externalId: "tmdb-39176",
  },
  {
    canonicalTitle: "Hard Boiled",
    originalTitle: "辣手神探",
    mediaType: MediaType.MOVIE,
    subType: "Action",
    releaseYear: 1992,
    status: MediaStatus.COMPLETED,
    country: "HK",
    language: "zh",
    genres: JSON.stringify(["Action", "Crime", "Thriller"]),
    description: "A Hong Kong detective and an undercover cop take down a ruthless arms smuggling operation.",
    rating: 7.7,
    popularity: 52000,
    duration: 128,
    sourceUrl: "https://www.themoviedb.org/movie/10495",
    sourceName: "TMDB",
    externalId: "tmdb-10495",
  },
] as const;
