import { MediaType, MediaStatus } from "@prisma/client";

export const televisionTitles = [
  {
    canonicalTitle: "Breaking Bad",
    originalTitle: "Breaking Bad",
    mediaType: MediaType.TELEVISION,
    subType: "Drama",
    releaseYear: 2008,
    endYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Drama", "Crime", "Thriller"]),
    description: "A chemistry teacher diagnosed with cancer turns to making drugs to secure his family's future.",
    rating: 9.5,
    popularity: 92000,
    episodeCount: 62,
    sourceUrl: "https://www.themoviedb.org/tv/1396",
    sourceName: "TMDB",
    externalId: "tv-1396",
  },
  {
    canonicalTitle: "The Wire",
    originalTitle: "The Wire",
    mediaType: MediaType.TELEVISION,
    subType: "Crime Drama",
    releaseYear: 2002,
    endYear: 2008,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Crime", "Drama", "Social Realism"]),
    description: "An in-depth look at Baltimore's inner city institutions and the drug trade from multiple perspectives.",
    rating: 9.3,
    popularity: 85000,
    episodeCount: 60,
    sourceUrl: "https://www.themoviedb.org/tv/1438",
    sourceName: "TMDB",
    externalId: "tv-1438",
  },
  {
    canonicalTitle: "Succession",
    originalTitle: "Succession",
    mediaType: MediaType.TELEVISION,
    subType: "Drama",
    releaseYear: 2018,
    endYear: 2023,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Drama", "Dark Comedy", "Satire"]),
    description: "The Roy family's dysfunctional power struggle over a global media empire.",
    rating: 8.8,
    popularity: 82000,
    episodeCount: 39,
    sourceUrl: "https://www.themoviedb.org/tv/63174",
    sourceName: "TMDB",
    externalId: "tv-63174",
  },
  {
    canonicalTitle: "Dark",
    originalTitle: "Dark",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 2017,
    endYear: 2020,
    status: MediaStatus.COMPLETED,
    country: "DE",
    language: "de",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Mystery", "Time Travel"]),
    description: "Children vanish in a German town, unraveling an intricate time travel conspiracy spanning several generations.",
    rating: 8.8,
    popularity: 80000,
    episodeCount: 26,
    sourceUrl: "https://www.themoviedb.org/tv/70523",
    sourceName: "TMDB",
    externalId: "tv-70523",
  },
  {
    canonicalTitle: "Severance",
    originalTitle: "Severance",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 2022,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Drama", "Mystery"]),
    description: "Employees of a company are surgically separated between their work and personal memories.",
    rating: 8.7,
    popularity: 78000,
    episodeCount: 18,
    sourceUrl: "https://www.themoviedb.org/tv/95396",
    sourceName: "TMDB",
    externalId: "tv-95396",
  },
  {
    canonicalTitle: "True Detective (Season 1)",
    originalTitle: "True Detective",
    mediaType: MediaType.TELEVISION,
    subType: "Crime Drama",
    releaseYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Crime", "Thriller", "Drama", "Mystery"]),
    description: "Two Louisiana detectives investigate a murder that spans 17 years and a terrifying cult.",
    rating: 9.0,
    popularity: 83000,
    episodeCount: 8,
    sourceUrl: "https://www.themoviedb.org/tv/46648",
    sourceName: "TMDB",
    externalId: "tv-46648",
  },
  {
    canonicalTitle: "Hannibal",
    originalTitle: "Hannibal",
    mediaType: MediaType.TELEVISION,
    subType: "Psychological Thriller",
    releaseYear: 2013,
    endYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Thriller", "Horror", "Crime", "Psychological"]),
    description: "FBI profiler Will Graham works with psychiatrist Hannibal Lecter, unaware Lecter is a serial killer.",
    rating: 8.6,
    popularity: 75000,
    episodeCount: 39,
    sourceUrl: "https://www.themoviedb.org/tv/40008",
    sourceName: "TMDB",
    externalId: "tv-40008",
  },
  {
    canonicalTitle: "Black Mirror",
    originalTitle: "Black Mirror",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi Anthology",
    releaseYear: 2011,
    status: MediaStatus.ONGOING,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Dystopia", "Technology"]),
    description: "An anthology series exploring the dark side of technology in near-future or parallel-present worlds.",
    rating: 8.8,
    popularity: 82000,
    episodeCount: 27,
    sourceUrl: "https://www.themoviedb.org/tv/42009",
    sourceName: "TMDB",
    externalId: "tv-42009",
  },
  {
    canonicalTitle: "The Expanse",
    originalTitle: "The Expanse",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 2015,
    endYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Thriller", "Hard Sci-Fi"]),
    description: "In a colonized solar system, a detective, a politician, and a ship's crew uncover a vast conspiracy.",
    rating: 8.5,
    popularity: 74000,
    episodeCount: 62,
    sourceUrl: "https://www.themoviedb.org/tv/63639",
    sourceName: "TMDB",
    externalId: "tv-63639",
  },
  {
    canonicalTitle: "Squid Game",
    originalTitle: "오징어 게임",
    mediaType: MediaType.TELEVISION,
    subType: "Thriller",
    releaseYear: 2021,
    status: MediaStatus.ONGOING,
    country: "KR",
    language: "ko",
    genres: JSON.stringify(["Thriller", "Drama", "Dystopia", "Action"]),
    description: "Financially desperate people compete in deadly children's games for a massive cash prize.",
    rating: 8.0,
    popularity: 90000,
    episodeCount: 9,
    sourceUrl: "https://www.themoviedb.org/tv/93405",
    sourceName: "TMDB",
    externalId: "tv-93405",
  },
  {
    canonicalTitle: "Twin Peaks",
    originalTitle: "Twin Peaks",
    mediaType: MediaType.TELEVISION,
    subType: "Mystery",
    releaseYear: 1990,
    endYear: 1991,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Mystery", "Drama", "Horror", "Surreal"]),
    description: "FBI agent Dale Cooper investigates the murder of a small-town homecoming queen in a logging community.",
    rating: 8.8,
    popularity: 70000,
    episodeCount: 30,
    sourceUrl: "https://www.themoviedb.org/tv/1920",
    sourceName: "TMDB",
    externalId: "tv-1920",
  },
  {
    canonicalTitle: "Buffy the Vampire Slayer",
    originalTitle: "Buffy the Vampire Slayer",
    mediaType: MediaType.TELEVISION,
    subType: "Fantasy",
    releaseYear: 1997,
    endYear: 2003,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Horror", "Drama", "Comedy"]),
    description: "A teenage girl destined to be the Slayer fights vampires, demons, and the forces of darkness.",
    rating: 8.1,
    popularity: 68000,
    episodeCount: 144,
    sourceUrl: "https://www.themoviedb.org/tv/95",
    sourceName: "TMDB",
    externalId: "tv-95",
  },
  {
    canonicalTitle: "Battlestar Galactica",
    originalTitle: "Battlestar Galactica",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 2004,
    endYear: 2009,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Action", "Thriller"]),
    description: "The remnants of humanity flee robot attackers across space while searching for mythical Earth.",
    rating: 8.7,
    popularity: 72000,
    episodeCount: 75,
    sourceUrl: "https://www.themoviedb.org/tv/1972",
    sourceName: "TMDB",
    externalId: "tv-1972",
  },
  {
    canonicalTitle: "Firefly",
    originalTitle: "Firefly",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi Western",
    releaseYear: 2002,
    endYear: 2003,
    status: MediaStatus.CANCELLED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Western", "Action", "Adventure"]),
    description: "A crew of outlaws flies a transport ship on the outer edges of a future solar system, taking odd jobs.",
    rating: 9.0,
    popularity: 70000,
    episodeCount: 14,
    sourceUrl: "https://www.themoviedb.org/tv/1437",
    sourceName: "TMDB",
    externalId: "tv-1437",
  },
  {
    canonicalTitle: "Money Heist",
    originalTitle: "La Casa de Papel",
    mediaType: MediaType.TELEVISION,
    subType: "Thriller",
    releaseYear: 2017,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "ES",
    language: "es",
    genres: JSON.stringify(["Thriller", "Crime", "Drama", "Heist"]),
    description: "A criminal mastermind and his crew execute an elaborate heist on the Royal Mint of Spain.",
    rating: 8.2,
    popularity: 85000,
    episodeCount: 41,
    sourceUrl: "https://www.themoviedb.org/tv/71446",
    sourceName: "TMDB",
    externalId: "tv-71446",
  },
  {
    canonicalTitle: "Stranger Things",
    originalTitle: "Stranger Things",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi Horror",
    releaseYear: 2016,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Horror", "Drama", "Supernatural"]),
    description: "A group of kids in 1980s Indiana encounter supernatural forces and a mysterious girl with psychic powers.",
    rating: 8.7,
    popularity: 88000,
    episodeCount: 34,
    sourceUrl: "https://www.themoviedb.org/tv/66732",
    sourceName: "TMDB",
    externalId: "tv-66732",
  },
  {
    canonicalTitle: "The Sopranos",
    originalTitle: "The Sopranos",
    mediaType: MediaType.TELEVISION,
    subType: "Crime Drama",
    releaseYear: 1999,
    endYear: 2007,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Crime", "Drama", "Thriller"]),
    description: "A New Jersey mob boss tries to balance his family life with his criminal empire while in therapy.",
    rating: 9.2,
    popularity: 86000,
    episodeCount: 86,
    sourceUrl: "https://www.themoviedb.org/tv/1398",
    sourceName: "TMDB",
    externalId: "tv-1398",
  },
  {
    canonicalTitle: "My Mister",
    originalTitle: "나의 아저씨",
    mediaType: MediaType.TELEVISION,
    subType: "Drama",
    releaseYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "KR",
    language: "ko",
    genres: JSON.stringify(["Drama", "Slice of Life", "Romance"]),
    description: "A middle-aged engineer and a young temp worker develop an unexpected bond over shared struggles.",
    rating: 9.2,
    popularity: 62000,
    episodeCount: 16,
    sourceUrl: "https://www.themoviedb.org/tv/76262",
    sourceName: "TMDB",
    externalId: "tv-76262",
  },
  {
    canonicalTitle: "Vincenzo",
    originalTitle: "빈센조",
    mediaType: MediaType.TELEVISION,
    subType: "Crime Drama",
    releaseYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "KR",
    language: "ko",
    genres: JSON.stringify(["Crime", "Drama", "Comedy", "Thriller"]),
    description: "An Italian-Korean mafia lawyer returns to Korea and ends up fighting a corrupt conglomerate his own way.",
    rating: 8.4,
    popularity: 68000,
    episodeCount: 20,
    sourceUrl: "https://www.themoviedb.org/tv/115713",
    sourceName: "TMDB",
    externalId: "tv-115713",
  },
  {
    canonicalTitle: "Star Trek: The Next Generation",
    originalTitle: "Star Trek: The Next Generation",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 1987,
    endYear: 1994,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Adventure", "Drama"]),
    description: "Captain Picard and the crew of the Enterprise-D explore the galaxy in the 24th century.",
    rating: 8.6,
    popularity: 72000,
    episodeCount: 178,
    sourceUrl: "https://www.themoviedb.org/tv/655",
    sourceName: "TMDB",
    externalId: "tv-655",
  },
  {
    canonicalTitle: "The Twilight Zone",
    originalTitle: "The Twilight Zone",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi Anthology",
    releaseYear: 1959,
    endYear: 1964,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Fantasy", "Horror", "Anthology"]),
    description: "An anthology series presenting stories of ordinary people who encounter extraordinary circumstances.",
    rating: 9.0,
    popularity: 65000,
    episodeCount: 156,
    sourceUrl: "https://www.themoviedb.org/tv/4614",
    sourceName: "TMDB",
    externalId: "tv-4614",
  },
  {
    canonicalTitle: "Game of Thrones",
    originalTitle: "Game of Thrones",
    mediaType: MediaType.TELEVISION,
    subType: "Fantasy",
    releaseYear: 2011,
    endYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Drama", "Action", "Political"]),
    description: "Noble families fight for the Iron Throne while an ancient evil awakens beyond the wall.",
    rating: 9.2,
    popularity: 95000,
    episodeCount: 73,
    sourceUrl: "https://www.themoviedb.org/tv/1399",
    sourceName: "TMDB",
    externalId: "tv-1399",
  },
  {
    canonicalTitle: "Over the Garden Wall",
    originalTitle: "Over the Garden Wall",
    mediaType: MediaType.TELEVISION,
    subType: "Animated Miniseries",
    releaseYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Animation", "Fantasy", "Mystery", "Fairy Tale"]),
    description: "Two brothers wander through a strange forest called the Unknown, trying to find their way home.",
    rating: 8.7,
    popularity: 62000,
    episodeCount: 10,
    sourceUrl: "https://www.themoviedb.org/tv/60059",
    sourceName: "TMDB",
    externalId: "tv-60059",
  },
  {
    canonicalTitle: "The X-Files",
    originalTitle: "The X-Files",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 1993,
    endYear: 2018,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Mystery", "Horror", "Thriller"]),
    description: "FBI agents investigate unsolved paranormal cases, uncovering government conspiracies along the way.",
    rating: 8.6,
    popularity: 74000,
    episodeCount: 218,
    sourceUrl: "https://www.themoviedb.org/tv/4087",
    sourceName: "TMDB",
    externalId: "tv-4087",
  },
  {
    canonicalTitle: "Babylon 5",
    originalTitle: "Babylon 5",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 1993,
    endYear: 1998,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Drama", "Political", "Space Opera"]),
    description: "A massive space station serves as the focal point for a galactic war between ancient forces.",
    rating: 8.3,
    popularity: 55000,
    episodeCount: 110,
    sourceUrl: "https://www.themoviedb.org/tv/1262",
    sourceName: "TMDB",
    externalId: "tv-1262",
  },
  {
    canonicalTitle: "Jonathan Strange & Mr Norrell",
    originalTitle: "Jonathan Strange & Mr Norrell",
    mediaType: MediaType.TELEVISION,
    subType: "Fantasy",
    releaseYear: 2015,
    status: MediaStatus.COMPLETED,
    country: "GB",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Historical", "Drama", "Mystery"]),
    description: "Two magicians in Napoleonic-era England attempt to restore magic to the country — with dangerous consequences.",
    rating: 7.9,
    popularity: 42000,
    episodeCount: 7,
    sourceUrl: "https://www.themoviedb.org/tv/62217",
    sourceName: "TMDB",
    externalId: "tv-62217",
  },
  {
    canonicalTitle: "Fringe",
    originalTitle: "Fringe",
    mediaType: MediaType.TELEVISION,
    subType: "Sci-Fi",
    releaseYear: 2008,
    endYear: 2013,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Thriller", "Mystery", "Drama"]),
    description: "An FBI agent works with a mad scientist and his son to investigate strange phenomena at the edge of science.",
    rating: 8.4,
    popularity: 68000,
    episodeCount: 100,
    sourceUrl: "https://www.themoviedb.org/tv/1705",
    sourceName: "TMDB",
    externalId: "tv-1705",
  },
] as const;
