import { MediaType, MediaStatus } from "@prisma/client";

export const webseriesTitles = [
  {
    canonicalTitle: "RWBY",
    originalTitle: "RWBY",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2013,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Action", "Adventure", "Anime-Style"]),
    description: "Four girls train at a combat school to fight Grimm creatures in a world where magic-like Dust powers technology.",
    rating: 7.7,
    popularity: 58000,
    sourceUrl: "https://www.themoviedb.org/tv/62741",
    sourceName: "TMDB",
    externalId: "ws-62741",
  },
  {
    canonicalTitle: "Hazbin Hotel",
    originalTitle: "Hazbin Hotel",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2019,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Dark Comedy", "Musical", "Fantasy", "Adult"]),
    description: "Hell's princess tries to rehabilitate demons through a hotel dedicated to redemption and return to Heaven.",
    rating: 8.1,
    popularity: 65000,
    sourceUrl: "https://www.themoviedb.org/tv/219070",
    sourceName: "TMDB",
    externalId: "ws-hazbin",
  },
  {
    canonicalTitle: "Helluva Boss",
    originalTitle: "Helluva Boss",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2020,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Dark Comedy", "Fantasy", "Adult", "Musical"]),
    description: "A demon assassin company in Hell takes contracts from the dead who want the living killed.",
    rating: 8.3,
    popularity: 62000,
    sourceUrl: "https://www.themoviedb.org/tv/131527",
    sourceName: "TMDB",
    externalId: "ws-helluva",
  },
  {
    canonicalTitle: "Red vs. Blue",
    originalTitle: "Red vs. Blue",
    mediaType: MediaType.WEB_SERIES,
    subType: "Machinima",
    releaseYear: 2003,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Comedy", "Sci-Fi", "Action", "Machinima"]),
    description: "Two teams of soldiers stationed in a canyon argue about nothing while stumbling into galactic conspiracies.",
    rating: 8.2,
    popularity: 52000,
    sourceUrl: "https://www.themoviedb.org/tv/47261",
    sourceName: "TMDB",
    externalId: "ws-rvb",
  },
  {
    canonicalTitle: "Epithet Erased",
    originalTitle: "Epithet Erased",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2019,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Comedy", "Adventure", "Superhero", "Parody"]),
    description: "A girl with a nonsense superpower investigates a museum robbery alongside a well-meaning criminal.",
    rating: 8.5,
    popularity: 38000,
    sourceUrl: "https://www.themoviedb.org/tv/100056",
    sourceName: "TMDB",
    externalId: "ws-epithet",
  },
  {
    canonicalTitle: "Murder Drones",
    originalTitle: "Murder Drones",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2023,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Dark Comedy", "Action", "Horror"]),
    description: "Worker drones scraping by on a desolate planet are hunted by disassembly units sent to eliminate them.",
    rating: 8.3,
    popularity: 52000,
    sourceUrl: "https://www.youtube.com/playlist?list=PLxbHSWHGAKTkrF7sCFJYBrBi1eMr7LZCD",
    sourceName: "YouTube",
    externalId: "ws-murder-drones",
  },
  {
    canonicalTitle: "gen:LOCK",
    originalTitle: "gen:LOCK",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2019,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Mecha", "Action", "Drama"]),
    description: "Soldiers upload their minds into giant mechs to fight an authoritarian force threatening freedom worldwide.",
    rating: 7.4,
    popularity: 40000,
    sourceUrl: "https://www.themoviedb.org/tv/90200",
    sourceName: "TMDB",
    externalId: "ws-genlock",
  },
  {
    canonicalTitle: "The Most Popular Girls in School",
    originalTitle: "The Most Popular Girls in School",
    mediaType: MediaType.WEB_SERIES,
    subType: "Comedy",
    releaseYear: 2012,
    endYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Comedy", "Parody", "Barbie"]),
    description: "A satirical comedy about high school politics and cheerleader drama, performed by plastic dolls.",
    rating: 8.0,
    popularity: 32000,
    sourceUrl: "https://www.youtube.com/playlist?list=PLr6Iq8gTtRSYGNf2Q-4pBXFaTyasG7zFN",
    sourceName: "YouTube",
    externalId: "ws-mpgis",
  },
  {
    canonicalTitle: "Critical Role (Campaign 1)",
    originalTitle: "Critical Role: Vox Machina",
    mediaType: MediaType.WEB_SERIES,
    subType: "Live Play",
    releaseYear: 2015,
    endYear: 2017,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Adventure", "Tabletop RPG", "Comedy"]),
    description: "A group of voice actors play Dungeons & Dragons in an immersive, character-driven fantasy campaign.",
    rating: 9.0,
    popularity: 62000,
    sourceUrl: "https://critrole.com",
    sourceName: "Critical Role",
    externalId: "ws-cr-c1",
  },
  {
    canonicalTitle: "Dimension 20: Fantasy High",
    originalTitle: "Dimension 20: Fantasy High",
    mediaType: MediaType.WEB_SERIES,
    subType: "Live Play",
    releaseYear: 2019,
    endYear: 2019,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Comedy", "High School", "Tabletop RPG"]),
    description: "Six teenagers at a magical high school try to stop an ancient evil awakening in their town.",
    rating: 9.2,
    popularity: 55000,
    sourceUrl: "https://www.dropout.tv/dimension-20",
    sourceName: "Dropout",
    externalId: "ws-d20-fh",
  },
  {
    canonicalTitle: "Bee and Puppycat: Lazy in Space",
    originalTitle: "Bee and Puppycat: Lazy in Space",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated",
    releaseYear: 2022,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Fantasy", "Slice of Life", "Comedy", "Magical"]),
    description: "The Netflix revival of the cult web series — a 20-something drifts through life with her alien cat-dog companion.",
    rating: 7.7,
    popularity: 38000,
    sourceUrl: "https://www.netflix.com/title/81248227",
    sourceName: "Netflix",
    externalId: "ws-bee-puppycat",
  },
  {
    canonicalTitle: "Infinity Train",
    originalTitle: "Infinity Train",
    mediaType: MediaType.WEB_SERIES,
    subType: "Animated Miniseries",
    releaseYear: 2019,
    endYear: 2021,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Sci-Fi", "Fantasy", "Mystery", "Drama"]),
    description: "Passengers wake on an infinite mysterious train and must solve puzzles in each car to reduce their exit number.",
    rating: 8.7,
    popularity: 60000,
    sourceUrl: "https://www.themoviedb.org/tv/92136",
    sourceName: "TMDB",
    externalId: "ws-infinity-train",
  },
  {
    canonicalTitle: "Terrible Writing Advice",
    originalTitle: "Terrible Writing Advice",
    mediaType: MediaType.WEB_SERIES,
    subType: "Educational Comedy",
    releaseYear: 2016,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Comedy", "Educational", "Writing", "Satire"]),
    description: "A deadpan YouTube series that teaches writing craft by demonstrating exactly what not to do.",
    rating: 8.7,
    popularity: 30000,
    sourceUrl: "https://www.youtube.com/@TerribleWritingAdvice",
    sourceName: "YouTube",
    externalId: "ws-twa",
  },
  {
    canonicalTitle: "Overly Sarcastic Productions",
    originalTitle: "Overly Sarcastic Productions",
    mediaType: MediaType.WEB_SERIES,
    subType: "Educational",
    releaseYear: 2012,
    status: MediaStatus.ONGOING,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Educational", "Comedy", "Literature", "Mythology"]),
    description: "A YouTube channel summarizing mythology, history, and literature with humor and hand-drawn animations.",
    rating: 8.9,
    popularity: 48000,
    sourceUrl: "https://www.youtube.com/@OverlySarcasticProductions",
    sourceName: "YouTube",
    externalId: "ws-osp",
  },
  {
    canonicalTitle: "Freeman's Mind",
    originalTitle: "Freeman's Mind",
    mediaType: MediaType.WEB_SERIES,
    subType: "Machinima Comedy",
    releaseYear: 2007,
    endYear: 2014,
    status: MediaStatus.COMPLETED,
    country: "US",
    language: "en",
    genres: JSON.stringify(["Comedy", "Gaming", "Machinima", "Parody"]),
    description: "The internal monologue of Half-Life's Gordon Freeman — narcissistic, unhinged, and surprisingly thoughtful.",
    rating: 8.6,
    popularity: 35000,
    sourceUrl: "https://www.youtube.com/playlist?list=PLDmfQoSLkfXfz6LPMS0qYsAd1QlEMsZ2N",
    sourceName: "YouTube",
    externalId: "ws-freemans-mind",
  },
] as const;
